Repository dynamiqs/dynamiqs, pull requests merged in 2023-12, with the labels that each got.

#368 Revert dynamic homepage
  docs/overrides/home.html
  docs/stylesheets/home.css
  docs/stylesheets/theme.css
Labels: 📚 documentation

#369 Fix flat batching
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/utils/utils.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_propagator.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/solver_tester.py
  tests/system.py
Labels: organisation, 🌀 solvers

#370 Internal renamings
  docs/tutorials/workflow.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/ode/adjoint_ode_solver.py
  dynamiqs/solvers/result.py
  dynamiqs/solvers/solver.py
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
  tests/solver_tester.py
  tests/system.py
Labels: organisation, 🌀 solvers

#364 Small fixes to documentation
  README.md
  docs/getting_started/examples.md
  docs/python_api/index.md
  docs/stylesheets/home.css
  dynamiqs/utils/tensor_types.py
  dynamiqs/utils/utils.py
  mkdocs.yml
Labels: 📚 documentation

#376 Fix black version
  pyproject.toml
Labels: bug

#372 Add `TimeTensor` [1/4]: replace `TDTensor` by `TimeTensor`
  dynamiqs/__init__.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/propagator.py
  dynamiqs/solvers/solver.py
  dynamiqs/solvers/utils/__init__.py
  dynamiqs/solvers/utils/td_tensor.py
  dynamiqs/time_tensor.py
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
  tests/test_time_tensor.py
Labels: organisation, 🌀 solvers

#374 Add TimeTensor [2/4]: implement `PWCTimeTensor`
  dynamiqs/time_tensor.py
  tests/test_time_tensor.py
Labels: feature, 🌀 solvers

#375 Add TimeTensor [3/4]: implement ModulatedTimeTensor
  dynamiqs/time_tensor.py
  tests/test_time_tensor.py
Labels: feature, 🌀 solvers

#378 Fix taskipy for windows
  pyproject.toml
Labels: bug, 🪛 tooling

#379 Fix `mplstyle()` for non TeX users and adjust default font
  docs/conftest.py
  dynamiqs/conftest.py
  dynamiqs/plots/utils.py
Labels: bug, 🎨 plot

#324 Backward Euler for sesolve
  dynamiqs/sesolve/backward_euler.py
  dynamiqs/sesolve/euler.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solver.py
  tests/sesolve/test_backward_euler.py
  tests/sesolve/test_beuler.py
Labels: feature

#381 Remove normalization in plot_wigner
  dynamiqs/plots/plots_wigner.py
Labels: 📚 documentation, feature

#382 Remove `TDArrayLike` outdated type
  dynamiqs/__init__.py
  dynamiqs/utils/tensor_types.py
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
Labels: organisation, 🌀 solvers

#384 Fix inverted file names in tests (for `sesolve` euler and backward euler)
  tests/sesolve/test_backward_euler.py
  tests/sesolve/test_euler.py
Labels: bug, 🎯 tests

#385 Fix `smesolve()` batching incompatibilities
  dynamiqs/smesolve/rouchon.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
Labels: bug, 🌀 solvers

#387 Remove duplicated checks for H type
  dynamiqs/mesolve/mesolve.py
  dynamiqs/smesolve/smesolve.py
Labels: organisation, 🌀 solvers

#388 Change API of slindbladian
  dynamiqs/utils/utils.py
  dynamiqs/utils/vectorization.py
Labels: feature

#390 Fix `dissipator()` return documentation
  dynamiqs/utils/utils.py
Labels: bug, 📚 documentation

#393 Enclose tqdm progress bar in try-finally block to ensure proper closing
  dynamiqs/solvers/ode/adjoint_ode_solver.py
  dynamiqs/solvers/ode/ode_solver.py
Labels: bug, 🌀 solvers

#386 Test `smesolve()`
  tests/smesolve/__init__.py
  tests/smesolve/monitored_system.py
  tests/smesolve/sme_solver_tester.py
  tests/smesolve/test_euler.py
  tests/smesolve/test_rouchon.py
Labels: feature, 🎯 tests
