Repository dynamiqs/dynamiqs, pull requests merged in 2023-07, with the labels that each got.

#148 Update tensprod for batched input states and for bras
  dynamiqs/utils/utils.py
Labels: 🚀 feature

#150 Separate public and solver-related utilities in separate folders
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/sesolve/propagator.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/ode/fixed_solver.py
  dynamiqs/solvers/propagator.py
  dynamiqs/solvers/solver.py
  dynamiqs/solvers/utils/td_tensor.py
  dynamiqs/solvers/utils/tensor_formatter.py
  dynamiqs/solvers/utils/utils.py
  dynamiqs/utils/progress_bar.py
Labels: 🗂️ organization

#149 Change doc header
  docs/overrides/partials/header.html
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: 📚 documentation

#155 Add result class
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solvers/ode/fixed_solver.py
  dynamiqs/solvers/result.py
  dynamiqs/solvers/solver.py
  tests/mesolve/me_solver_tester.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/se_solver_tester.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
Labels: 🚀 feature

#154 Fix Rouchon1_5 and implement caching
  dynamiqs/mesolve/rouchon.py
  dynamiqs/solvers/utils/utils.py
  tests/mesolve/test_rouchon.py
Labels: 🐛 bug, 🚀 feature

#152 Add table that summarizes all functions in documentation API
  docs/reference/index.md
  docs/reference/utils/operators.md
  docs/reference/utils/states.md
  docs/reference/utils/tensor_types.md
  docs/reference/utils/wigner.md
  docs/stylesheets/extra.css
  docs/templates/python/material/module.html
  docs/templates/python/material/table.html
  dynamiqs/utils/tensor_types.py
  mkdocs.yml
Labels: 📚 documentation

#156 Update run_nograd with inference_mode
  dynamiqs/solvers/solver.py
Labels: 🚀 feature

#141 Add `smesolve`
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/euler.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/ode/fixed_solver.py
  dynamiqs/solvers/propagator.py
  dynamiqs/solvers/result.py
  dynamiqs/solvers/solver.py
  dynamiqs/solvers/utils/__init__.py
  dynamiqs/solvers/utils/utils.py
Labels: 🚀 feature, topic: smesolve

#159 Fix options
  dynamiqs/options.py
Labels: 🐛 bug

#160 Fix attribute access error on option being None
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
Labels: 🐛 bug

#158 Improve README
  .github/workflows/publish-doc.yml
  README.md
  docs/index.md
Labels: 📚 documentation

#153 Document all remaining utility functions
  dynamiqs/utils/operators.py
  dynamiqs/utils/states.py
  dynamiqs/utils/tensor_types.py
  dynamiqs/utils/wigner.py
Labels: 📚 documentation

#161 Fix for two-line parameters when deploying doc
  docs/stylesheets/extra.css
Labels: 🐛 bug, 📚 documentation

#157 Separate doc page for each function + summary tables
  docs/generate_reference.py
  docs/reference/index.md
  docs/reference/navigation.md
  docs/reference/solvers.md
  docs/reference/solvers/mesolve.md
  docs/reference/solvers/sesolve.md
  docs/reference/solvers/smesolve.md
  docs/reference/utils.md
  docs/reference/utils/operators.md
  docs/reference/utils/states.md
  docs/reference/utils/tensor_types.md
  docs/reference/utils/utils.md
  docs/reference/utils/wigner.md
  docs/stylesheets/extra.css
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/states.py
  dynamiqs/utils/tensor_types.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/wigners.py
  mkdocs.yml
  pyproject.toml
Labels: 📚 documentation

#164 Minor doc fixes
  README.md
  docs/generate_python_api.py
  docs/generate_reference.py
  docs/index.md
  docs/python_api/navigation.md
  docs/python_api/solvers.md
  docs/python_api/solvers/mesolve.md
  docs/python_api/solvers/sesolve.md
  docs/python_api/solvers/smesolve.md
  docs/python_api/utils.md
  docs/reference/navigation.md
  docs/reference/solvers.md
  docs/reference/solvers/mesolve.md
  docs/reference/solvers/sesolve.md
  docs/reference/solvers/smesolve.md
  docs/stylesheets/extra.css
  docs/templates/python/material/docstring/parameters.html
  docs/templates/python/material/docstring/returns.html
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/utils/tensor_formatter.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/states.py
  dynamiqs/utils/tensor_types.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/wigners.py
  mkdocs.yml
  tests/mesolve/me_solver_tester.py
  tests/sesolve/se_solver_tester.py
Labels: 🐛 bug, 📚 documentation

#169 Add doctest
  CONTRIBUTING.md
  docs/conftest.py
  docs/getting_started/index.md
  dynamiqs/conftest.py
  dynamiqs/solvers/utils/utils.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/states.py
  pyproject.toml
Labels: 🔧 tests

#171 Add `__str__` and `__repr__` for options class
  dynamiqs/options.py
Labels: 🚀 feature

#165 Merge `Rouchon1` and `Rouchon1_5`
  dynamiqs/mesolve/mesolve.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/options.py
  tests/mesolve/test_rouchon.py
Labels: 🗂️ organization

#172 Uniform and cleaner dtype and device handling
  dynamiqs/mesolve/mesolve.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/options.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/solver.py
  dynamiqs/solvers/utils/td_tensor.py
  dynamiqs/solvers/utils/tensor_formatter.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/states.py
  dynamiqs/utils/tensor_types.py
Labels: 🐛 bug

#175 Add `ArrayLike` type to replace `TensorLike` and `OperatorLike`
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/utils/td_tensor.py
  dynamiqs/solvers/utils/tensor_formatter.py
  dynamiqs/utils/tensor_types.py
  tests/mesolve/open_system.py
Labels: 🗂️ organization

#176 Simplify tensor batching
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/sesolve/propagator.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/utils/__init__.py
  dynamiqs/solvers/utils/batching.py
  dynamiqs/solvers/utils/tensor_formatter.py
Labels: 🗂️ organization

#177 Improve documentation (add examples and latex formulas)
  dynamiqs/solvers/result.py
  dynamiqs/solvers/utils/utils.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/states.py
  dynamiqs/utils/tensor_types.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/wigners.py
  tests/mesolve/me_solver_tester.py
  tests/sesolve/se_solver_tester.py
Labels: 📚 documentation

#180 Clean up getting started page
  docs/getting_started/_foo.md
  docs/getting_started/index.md
Labels: 📚 documentation

#182 Fix Pauli operator name
  dynamiqs/utils/operators.py
Labels: 📚 documentation

#178 New logo
  README.md
  docs/index.md
  docs/media/dynamiqs-logo-large.png
  docs/media/dynamiqs-logo.png
  docs/media/dynamiqs_logo.png
  docs/media/favicon.ico
  docs/media/logo-dark-large.png
  docs/media/logo-dark.png
  docs/media/logo-inverted-large.png
  docs/media/logo-inverted.png
  docs/media/logo-large.png
  docs/media/logo-white-large.png
  docs/media/logo-white.png
  docs/media/logo.png
  docs/media/logo_white.png
Labels: 🚀 feature

#184 Basic filling for documentation website
  docs/getting_started/contributing.md
  docs/getting_started/discussion.md
  docs/getting_started/examples.md
  docs/getting_started/first_steps.md
  docs/getting_started/index.md
  docs/getting_started/installation.md
  docs/index.md
  docs/tutorials/ecd.md
  docs/tutorials/index.md
  docs/tutorials/optimal_control.md
  docs/tutorials/snap.md
  mkdocs.yml
Labels: 📚 documentation

#185 Change header color
  docs/stylesheets/extra.css
Labels: 📚 documentation

#186 Format doc footer with copyright notice
  mkdocs.yml
Labels: 📚 documentation

#187 Homepage
  docs/getting_started/index.md
  docs/getting_started/whatis.md
  docs/index.md
  docs/overrides/home.html
  docs/stylesheets/extra.css
  docs/stylesheets/home.css
  mkdocs.yml
Labels: 📚 documentation
