Repository dynamiqs/dynamiqs, pull requests merged in 2023-11, with the labels that each got.

#274 Fix `tmeas` device/dtype
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
Labels: 🐛 bug

#273 Improve error message on non-aligned dt
  dynamiqs/solvers/ode/fixed_solver.py
Labels: 🚀 feature

#275 Rouchon1 normalisation
  dynamiqs/mesolve/rouchon.py
  dynamiqs/solver.py
  dynamiqs/solvers/utils/td_tensor.py
  dynamiqs/solvers/utils/utils.py
  tests/mesolve/test_rouchon.py
Labels: 🚀 feature

#277 Refactor rouchon ME solver
  dynamiqs/mesolve/rouchon.py
  dynamiqs/solver.py
  dynamiqs/solvers/utils/utils.py
  tests/mesolve/test_rouchon.py
Labels: 🗂️ organization

#279 Change python version for doc publication
  .github/workflows/publish-doc.yml
Labels: 🐛 bug

#280 Fix python version in CI
  .github/workflows/publish-doc.yml
Labels: 🐛 bug, 📚 documentation

#278 Add tutorial on closed quantum systems simulation
  docs/stylesheets/extra.css
  docs/stylesheets/theme.css
  docs/tutorials/closed-system.md
  mkdocs.yml
Labels: 📚 documentation

#281 Fix workflow tutorial
  docs/tutorials/workflow.ipynb
  dynamiqs/solvers/result.py
Labels: 📚 documentation

#282 Remove collapser from jupyter notebook tutorials
  docs/stylesheets/jupyter.css
Labels: 📚 documentation

#283 Add tutorial on open quantum systems simulation
  docs/tutorials/closed-system.md
  docs/tutorials/open-system.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/vectorization.py
  mkdocs.yml
Labels: 📚 documentation

#285 Tutorial on defining Hamiltonians
  docs/tutorials/closed-system.md
  docs/tutorials/open-system.md
  docs/tutorials/td-system.md
  mkdocs.yml
Labels: 📚 documentation

#287 Less formal style in td-tensor.md
  docs/tutorials/td-system.md
Labels: 📚 documentation

#286 Modify navigation
  docs/getting_started/_foo.md
  docs/getting_started/index.md
  docs/python_api/index.md
  docs/python_api/navigation.md
  docs/python_api/solvers.md
  docs/python_api/utils.md
  docs/templates/python/material/table.html
  docs/tutorials/index.md
  docs/tutorials/open-system.md
  docs/tutorials/td-system.md
  docs/tutorials/workflow.ipynb
  mkdocs.yml
Labels: 📚 documentation

#297 Automatically generated figures in the doc
  .github/workflows/publish-doc.yml
  .gitignore
  CONTRIBUTING.md
  docs/conftest.py
  docs/figs-code/.gitkeep
  docs/figs-docs/.gitkeep
  docs/getting_started/contributing.md
  docs/stylesheets/extra.css
  dynamiqs/conftest.py
  dynamiqs/utils/tensor_types.py
  dynamiqs/utils/utils.py
  pyproject.toml
  pytest.ini
Labels: 📚 documentation

#298 Add back workflow figure
  docs/conftest.py
  docs/tutorials/workflow.md
  dynamiqs/conftest.py
Labels: 📚 documentation

#299 Add full width figure
  docs/conftest.py
  docs/stylesheets/extra.css
  docs/tutorials/workflow.md
Labels: 📚 documentation

#300 Add WIP documentation for plotting function
  docs/generate_python_api.py
  docs/python_api/index.md
  docs/stylesheets/extra.css
  docs/tutorials/workflow.md
  dynamiqs/conftest.py
  dynamiqs/plots/misc.py
  dynamiqs/plots/utils.py
  mkdocs.yml
Labels: 📚 documentation

#290 Fix spre and spost
  dynamiqs/utils/vectorization.py
  mkdocs.yml
Labels: 🐛 bug

#301 Modify behavior of dq.coherent
  dynamiqs/utils/operators.py
  dynamiqs/utils/states.py
  dynamiqs/utils/tensor_types.py
Labels: 🚀 feature

#288 Batching tutorial
  docs/conftest.py
  docs/stylesheets/extra.css
  docs/stylesheets/home.css
  docs/tutorials/batching.md
  docs/tutorials/workflow.md
  mkdocs.yml
Labels: 📚 documentation

#303 Fix lexers and remove "render" from doc HTML
  docs/hooks.py
  docs/overrides/partials/content.html
  docs/tutorials/closed-system.md
  docs/tutorials/defining-hamiltonians.md
  docs/tutorials/open-system.md
  mkdocs.yml
  pyproject.toml
Labels: 📚 documentation

#306 Add benchmark System class and TransmonGate class
  benchmarks/__init__.py
  benchmarks/systems/__init__.py
  benchmarks/systems/system.py
  benchmarks/systems/transmon_gate.py
Labels: ⏱️ benchmarks

#307 Add README to systems
  benchmarks/systems/README.md
Labels: ⏱️ benchmarks

#308 Add benchmark system: CatCNOT
  benchmarks/systems/README.md
  benchmarks/systems/cat_cnot.py
Labels: ⏱️ benchmarks

#311 Fix documentation hook to filter lines
  docs/conftest.py
  docs/hooks.py
  docs/overrides/partials/content.html
  docs/tutorials/workflow.md
  dynamiqs/conftest.py
  dynamiqs/plots/misc.py
Labels: 🐛 bug, 📚 documentation

#309 Fix vectorization
  docs/javascripts/katex.js
  dynamiqs/utils/vectorization.py
Labels: 🐛 bug, 📚 documentation

#312 Minor doc improvements (zoomable images, remove warning)
  mkdocs.yml
  pyproject.toml
Labels: 📚 documentation

#314 Fix wigner
  dynamiqs/utils/wigners.py
Labels: 🐛 bug

#313 Add plot wigner
  docs/stylesheets/extra.css
  docs/tutorials/workflow.md
  dynamiqs/plots/misc.py
  dynamiqs/utils/wigners.py
  mkdocs.yml
Labels: 🚀 feature

#317 Custom colormap for Wigners
  dynamiqs/plots/__init__.py
  dynamiqs/plots/misc.py
Labels: 📚 documentation

#316 Add `plot_wigner_mosaic`
  docs/tutorials/batching.md
  docs/tutorials/closed-system.md
  docs/tutorials/open-system.md
  docs/tutorials/workflow.md
  dynamiqs/plots/misc.py
  dynamiqs/plots/utils.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/vectorization.py
  mkdocs.yml
Labels: 🚀 feature

#319 Remove line dividers in tutorials
  docs/tutorials/batching.md
  docs/tutorials/closed-system.md
  docs/tutorials/defining-hamiltonians.md
  docs/tutorials/open-system.md
  docs/tutorials/workflow.md
Labels: 📚 documentation

#323 Fix black version
  pyproject.toml
Labels: 🗂️ organization

#276 Add tests for time-dependent problems
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_propagator.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/solver_tester.py
Labels: 🔧 tests

#266 [1/6] Create file for adjoint autograd
  dynamiqs/solvers/ode/adjoint_autograd.py
  dynamiqs/solvers/ode/fixed_solver.py
Labels: 🗂️ organization

#267 [2/6] Refactor adaptive solver
  dynamiqs/solvers/ode/adaptive_solver.py
Labels: 🗂️ organization

#268 [3/6] Refactor fixed solver
  dynamiqs/mesolve/euler.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/solvers/ode/adjoint_autograd.py
  dynamiqs/solvers/ode/fixed_solver.py
Labels: 🗂️ organization

#269 [4/6] Default time to Solver class
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/ode/adjoint_autograd.py
  dynamiqs/solvers/ode/fixed_solver.py
  dynamiqs/solvers/propagator.py
  dynamiqs/solvers/solver.py
Labels: 🗂️ organization

#270 [5/6] Adjoint Dopri5 and tests
  dynamiqs/mesolve/adaptive.py
  dynamiqs/sesolve/adaptive.py
  dynamiqs/solver.py
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/ode/adjoint_autograd.py
  tests/mesolve/test_adaptive.py
  tests/solver_tester.py
Labels: 🚀 feature

#272 [6/6] Merge fixed and adaptive adjoint
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/ode/adjoint_autograd.py
  dynamiqs/solvers/ode/fixed_solver.py
Labels: 🗂️ organization

#302 [7/6] Fix out of bounds error if tsave[0] != 0
  dynamiqs/solvers/ode/adjoint_autograd.py
Labels: 🐛 bug

#322 Fix cavity tests
  tests/README.md
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_euler.py
Labels: 🐛 bug, 🔧 tests

#318 [1/2] Split open and closed systems in tests
  benchmarks/systems/system.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_propagator.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/solver_tester.py
  tests/system.py
Labels: 🚀 feature

#305 Add the sharp bits
  docs/getting_started/sharp-bits.md
  mkdocs.yml
Labels: 📚 documentation

#336 Add ndim and shape to TDTensor
  dynamiqs/solvers/utils/td_tensor.py
Labels: 🚀 feature

#335 Add basis, alias of fock
  docs/templates/python/material/table.html
  dynamiqs/utils/states.py
  mkdocs.yml
Labels: 🚀 feature

#338 Use attribute doc style for properties docstring
  dynamiqs/solvers/utils/td_tensor.py
Labels: 📚 documentation

#339 Minor fix to open system tutorial
  docs/tutorials/open-system.md
Labels: 🐛 bug, 📚 documentation

#344 Add pip list to CI
  .github/workflows/ci.yml
  .github/workflows/publish-doc.yml
Labels: 🗂️ organization

#346 Fix pycon lexer not recognised by sybil
  docs/conftest.py
  docs/getting_started/sharp-bits.md
Labels: bug, 📚 documentation

#325 [2/3] Batched dissipators
  dynamiqs/mesolve/adaptive.py
  dynamiqs/mesolve/euler.py
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/mesolve/propagator.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/euler.py
  dynamiqs/smesolve/rouchon.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/utils/batching.py
  dynamiqs/solvers/utils/utils.py
  dynamiqs/utils/vectorization.py
  tests/mesolve/open_system.py
  tests/solver_tester.py
Labels: feature

#343 Fix batching all around, and replace einsums with matmuls
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/sesolve/adaptive.py
  dynamiqs/sesolve/euler.py
  dynamiqs/sesolve/propagator.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/rouchon.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/utils/batching.py
  dynamiqs/solvers/utils/td_tensor.py
  dynamiqs/solvers/utils/utils.py
Labels: organisation, performance

#348 Fix inverted y axis in `plot_pwc_pulse()`
  dynamiqs/plots/misc.py
Labels: bug, 🎨 plot

#345 Improve sharp bits documentation page
  docs/conftest.py
  docs/getting_started/sharp-bits.md
  docs/tutorials/batching-simulations.md
  docs/tutorials/computing-gradients.md
  docs/tutorials/defining-hamiltonians.md
  mkdocs.yml
Labels: 📚 documentation

#347 Add `dq.mpow()` for matrix power shortcut
  docs/getting_started/sharp-bits.md
  docs/tutorials/defining-hamiltonians.md
  dynamiqs/utils/utils.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#349 Fix wrong exponent in sharp bits tutorial
  docs/getting_started/sharp-bits.md
Labels: bug, 📚 documentation

#350 Split plot functions into multiple files
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/conftest.py
  dynamiqs/plots/__init__.py
  dynamiqs/plots/namespace.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/plots/plots_wigner.py
  mkdocs.yml
Labels: organisation, 🎨 plot

#351 Fix adjoint
  dynamiqs/mesolve/adaptive.py
  dynamiqs/sesolve/adaptive.py
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/ode/adjoint_ode_solver.py
  tests/mesolve/test_adaptive.py
Labels: bug, 🌀 solvers

#352 Fix adjoint memory usage
  dynamiqs/solvers/ode/adaptive_solver.py
  tests/mesolve/test_adaptive.py
Labels: bug, 🌀 solvers

#356 Fix Sybil CI
  docs/conftest.py
Labels: bug

#357 Fix sybil update
  docs/conftest.py
  docs/hooks.py
  docs/tutorials/batching-simulations.md
  dynamiqs/conftest.py
  pyproject.toml
Labels: bug, 📚 documentation

#355 Wavy homepage
  docs/overrides/home.html
  docs/stylesheets/home.css
  docs/stylesheets/theme.css
Labels: 📚 documentation

#353 Small fixes to doc
  README.md
  docs/getting_started/examples.md
  docs/getting_started/index.md
  docs/getting_started/whatis.md
  docs/stylesheets/theme.css
Labels: 📚 documentation

#359 Fix `pwc_pulse()` index
  dynamiqs/utils/optimal_control.py
Labels: bug, 🕹️ quantum control

#360 Add `rand_real()`
  dynamiqs/utils/optimal_control.py
  mkdocs.yml
Labels: feature, 🕹️ quantum control

#361 Better documentation of the choice for `rand_complex()`
  dynamiqs/conftest.py
  dynamiqs/plots/utils.py
  dynamiqs/utils/optimal_control.py
Labels: feature, 🕹️ quantum control

#363 Simplify batching internally
  dynamiqs/mesolve/adaptive.py
  dynamiqs/mesolve/euler.py
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/mesolve/propagator.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/sesolve/adaptive.py
  dynamiqs/sesolve/euler.py
  dynamiqs/sesolve/propagator.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/euler.py
  dynamiqs/smesolve/rouchon.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/solver.py
  dynamiqs/solvers/utils/__init__.py
  dynamiqs/solvers/utils/batching.py
  dynamiqs/solvers/utils/td_tensor.py
  dynamiqs/solvers/utils/utils.py
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
  tests/solver_tester.py
  tests/system.py
Labels: organisation, 🌀 solvers

#362 Add even cat example to `plot_fock()`
  dynamiqs/plots/plots_fock.py
Labels: 📚 documentation, feature

#354 Add `plot_hinton()`
  docs/python_api/index.md
  dynamiqs/conftest.py
  dynamiqs/plots/__init__.py
  dynamiqs/plots/namespace.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_hinton.py
  dynamiqs/plots/utils.py
  mkdocs.yml
  pyproject.toml
Labels: feature, 🎨 plot
