Repository dynamiqs/dynamiqs, pull requests merged in 2023-04, with the labels that each got.

#53 Proposal for a testing framework
  CONTRIBUTING.md
  pyproject.toml
  pytest.ini
  tests/mesolve/mesolver_test.py
  tests/mesolve/open_system.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/sesolver_test.py
  tests/sesolve/test_euler.py
Labels: 🔧 tests

#55 Define a default progress bar format
  torchqdynamics/odeint.py
  torchqdynamics/progress_bar.py
Labels: 🚀 feature

#64 Fix rotating cavity `t_end` inhomogeneous
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
Labels: 🔧 tests

#56 Add `ptrace` function
  torchqdynamics/solver_utils.py
  torchqdynamics/utils.py
Labels: 🚀 feature

#57 Various utility functions
  tests/mesolve/open_system.py
  torchqdynamics/__init__.py
  torchqdynamics/adaptive.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/odeint.py
  torchqdynamics/operators.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/smesolve.py
  torchqdynamics/solver_utils.py
  torchqdynamics/states.py
  torchqdynamics/types.py
  torchqdynamics/utils.py
Labels: 🚀 feature

#63 Various fixes and improvements
  tests/test_utils.py
  torchqdynamics/adaptive.py
  torchqdynamics/mesolve/adaptive.py
  torchqdynamics/mesolve/euler.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/odeint.py
  torchqdynamics/sesolve/adaptive.py
  torchqdynamics/sesolve/euler.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/solver_utils.py
  torchqdynamics/tensor_types.py
Labels: 🐛 bug, 🚀 feature

#66 Fix `dtype` and `device` throughout the code
  tests/test_utils.py
  torchqdynamics/__init__.py
  torchqdynamics/adaptive.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/odeint.py
  torchqdynamics/operators.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/states.py
  torchqdynamics/tensor_types.py
  torchqdynamics/utils.py
Labels: 🐛 bug, 🚀 feature

#67 Replace QuTiP utils by library utils in tests (+ various minor fixes)
  tests/mesolve/open_system.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_mesolve.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  torchqdynamics/mesolve/euler.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/sesolve/euler.py
  torchqdynamics/solver_utils.py
Labels: 🔧 tests

#70 Move save logic from `odeint` to `ForwardQSolver`
  torchqdynamics/mesolve/adaptive.py
  torchqdynamics/mesolve/euler.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/odeint.py
  torchqdynamics/sesolve/adaptive.py
  torchqdynamics/sesolve/euler.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/solver_options.py
Labels: 🚀 feature, topic: odeint

#71 Make solvers independent from `odeint`
  tests/sesolve/test_propagator.py
  torchqdynamics/mesolve/adaptive.py
  torchqdynamics/mesolve/euler.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/mesolve/solver_options.py
  torchqdynamics/ode_adjoint_qsolver.py
  torchqdynamics/ode_forward_qsolver.py
  torchqdynamics/odeint.py
  torchqdynamics/qsolver.py
  torchqdynamics/sesolve/adaptive.py
  torchqdynamics/sesolve/euler.py
  torchqdynamics/sesolve/propagator.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/sesolve/solver_options.py
  torchqdynamics/solver.py
  torchqdynamics/solver_options.py
Labels: 🚀 feature

#73 Small renamings
  setup.cfg
  tests/mesolve/mesolver_test.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/sesolver_test.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  torchqdynamics/__init__.py
  torchqdynamics/adaptive_ode_solver.py
  torchqdynamics/mesolve/adaptive.py
  torchqdynamics/mesolve/euler.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/options.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/ode_adjoint_solver.py
  torchqdynamics/ode_forward_solver.py
  torchqdynamics/options.py
  torchqdynamics/qsolver.py
  torchqdynamics/sesolve/adaptive.py
  torchqdynamics/sesolve/euler.py
  torchqdynamics/sesolve/options.py
  torchqdynamics/sesolve/propagator.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/sesolve/solver_options.py
  torchqdynamics/solver.py
Labels: 🗂️ organization

#75 Some more renaming and reorganization
  tests/mesolve/mesolver_tester.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/sesolver_tester.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/utils/__init__.py
  tests/utils/test_utils.py
  torchqdynamics/__init__.py
  torchqdynamics/mesolve/adaptive.py
  torchqdynamics/mesolve/euler.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/ode/__init__.py
  torchqdynamics/ode/adaptive_ode_integrator.py
  torchqdynamics/ode/adjoint_solver.py
  torchqdynamics/ode/forward_solver.py
  torchqdynamics/sesolve/adaptive.py
  torchqdynamics/sesolve/euler.py
  torchqdynamics/sesolve/propagator.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/smesolve/__init__.py
  torchqdynamics/smesolve/smesolve.py
  torchqdynamics/solver.py
  torchqdynamics/utils/__init__.py
  torchqdynamics/utils/operators.py
  torchqdynamics/utils/progress_bar.py
  torchqdynamics/utils/solver_utils.py
  torchqdynamics/utils/states.py
  torchqdynamics/utils/tensor_types.py
  torchqdynamics/utils/utils.py
Labels: 🗂️ organization

#76 Add adaptive solver tests
  tests/mesolve/test_adaptive.py
  tests/sesolve/test_adaptive.py
  torchqdynamics/ode/forward_solver.py
  torchqdynamics/solver.py
Labels: 🔧 tests

#77 Add adjoint state gradients tests
  tests/mesolve/mesolver_tester.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/ode/adjoint_solver.py
  torchqdynamics/ode/forward_solver.py
Labels: 🔧 tests

#81 Fix bug in bosonic operator creation functions
  torchqdynamics/utils/operators.py
Labels: 🐛 bug

#82 Fix bug in `tq.coherent`
  torchqdynamics/utils/states.py
Labels: 🐛 bug
