Repository dynamiqs/dynamiqs, pull requests merged in 2023-08, with the labels that each got.

#183 Add documentation examples to utils
  docs/stylesheets/extra.css
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/solvers/ode/fixed_solver.py
  dynamiqs/solvers/utils/utils.py
  dynamiqs/utils/utils.py
Labels: 📚 documentation

#167 Test autograd and adjoint from analytic expressions
  tests/mesolve/me_solver_tester.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/se_solver_tester.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
Labels: 🔧 tests

#168 Unify solvers tests under the same base class
  tests/mesolve/me_solver_tester.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/se_solver_tester.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/solver_tester.py
  tests/system.py
Labels: 🔧 tests

#188 Fix result formatting bug
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
Labels: 🐛 bug

#166 Refactor tests
  tests/mesolve/me_solver_tester.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/se_solver_tester.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/solver_tester.py
  tests/system.py
Labels: 🔧 tests

#189 Favicon fix
  docs/media/favicon.ico
  docs/media/favicon.png
  docs/media/favicon.svg
  docs/overrides/main.html
  mkdocs.yml
Labels: 📚 documentation

#193 Fix installation instructions
  README.md
  docs/getting_started/installation.md
  pyproject.toml
Labels: 🐛 bug

#196 Add `__version__` fetched from `pyproject.toml`
  dynamiqs/__init__.py
Labels: 🚀 feature
