Repository dynamiqs/dynamiqs, pull requests merged in 2023-09, with the labels that each got.

#198 Fix undefined `y_save` in `solver.py` if `save_states` is False
  dynamiqs/solvers/solver.py
Labels: 🐛 bug

#197 Fix incorrect `torch.squeeze` usage
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
Labels: 🐛 bug

#199 Add number and parity operators
  docs/python_api/navigation.md
  dynamiqs/utils/operators.py
Labels: 🚀 feature

#200 Replace GPU enabled by GPU Accelerated on front page
  docs/overrides/home.html
Labels: 📚 documentation

#201 Rename internal variables
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/rouchon.py
Labels: 🗂️ organization

#202 Documentation homepage coloring
  docs/stylesheets/extra.css
  docs/stylesheets/home.css
Labels: 📚 documentation

#204 Dictionary API for solver options
  README.md
  docs/getting_started/examples.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/options.py
  dynamiqs/solvers/result.py
  dynamiqs/solvers/solver.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/solver_tester.py
  tests/system.py
Labels: 🗂️ organization

#208 Add `Propagator` solver for `mesolve` and vectorization utilities
  docs/generate_python_api.py
  docs/python_api/navigation.md
  docs/python_api/utils.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/mesolve/propagator.py
  dynamiqs/sesolve/propagator.py
  dynamiqs/solvers/propagator.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/vectorization.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_propagator.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_propagator.py
Labels: 🚀 feature, topic: mesolve

#210 Support batched tensors in `to_qutip`
  dynamiqs/utils/tensor_types.py
Labels: 🚀 feature

#203 Add Rouchon solver of order 1 for SME
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/smesolve/euler.py
  dynamiqs/smesolve/rouchon.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/options.py
Labels: 🚀 feature, topic: smesolve

#216 Round time difference in propagator solvers to prevent useless cache reloading
  dynamiqs/solvers/propagator.py
Labels: 🐛 bug

#219 Add `dq.dag` to compute the adjoint
  docs/python_api/navigation.md
  dynamiqs/utils/utils.py
Labels: 🚀 feature

#205 Document solvers
  docs/python_api/solvers.md
  docs/python_api/solvers/mesolve.md
  docs/python_api/solvers/sesolve.md
  docs/python_api/solvers/smesolve.md
  docs/python_api/utils.md
  docs/stylesheets/extra.css
  docs/templates/python/material/docstring/admonition.html
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
Labels: 📚 documentation

#206 Add module name to function headers in API
  docs/generate_python_api.py
  docs/python_api/solvers/mesolve.md
  docs/python_api/solvers/sesolve.md
  docs/python_api/solvers/smesolve.md
  docs/stylesheets/extra.css
  docs/templates/python/material/function.html
Labels: 📚 documentation

#211 Add mkdocs-jupyter and corresponding formatting for tutorials
  docs/stylesheets/extra.css
  docs/stylesheets/jupyter.css
  docs/tutorials/example.ipynb
  mkdocs.yml
  pyproject.toml
Labels: 📚 documentation

#212 Clean up CSS
  docs/stylesheets/extra.css
  docs/stylesheets/home.css
  docs/stylesheets/jupyter.css
  docs/stylesheets/theme.css
  mkdocs.yml
Labels: 📚 documentation

#213 Convert "First examples" to ipynb
  docs/getting_started/examples.ipynb
  docs/getting_started/examples.md
  mkdocs.yml
Labels: 📚 documentation

#217 Workflow tutorial
  docs/tutorials/example.ipynb
  docs/tutorials/workflow.ipynb
  mkdocs.yml
Labels: 📚 documentation

#220 Fix ci
  docs/getting_started/examples.ipynb
  docs/templates/python/material/function.html
Labels: 🐛 bug

#207 Align some of utils API with qutip
  docs/python_api/navigation.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/utils/utils.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/wigners.py
Labels: 📚 documentation

#214 Add utilities for quantum optimal control
  docs/generate_python_api.py
  docs/python_api/navigation.md
  dynamiqs/utils/__init__.py
  dynamiqs/utils/optimal_control.py
Labels: 🚀 feature

#221 Documentation styling
  docs/generate_python_api.py
  docs/getting_started/index.md
  docs/python_api/solvers.md
  docs/python_api/solvers/mesolve.md
  docs/python_api/solvers/sesolve.md
  docs/python_api/solvers/smesolve.md
  docs/stylesheets/extra.css
  docs/templates/python/material/function.html
  docs/tutorials/index.md
Labels: 📚 documentation

#222 Katex
  docs/javascripts/katex.js
  docs/javascripts/mathjax.js
  mkdocs.yml
Labels: 📚 documentation

#224 Rename `t_save` to `tsave`
  README.md
  docs/getting_started/examples.ipynb
  docs/tutorials/workflow.ipynb
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/ode/fixed_solver.py
  dynamiqs/solvers/options.py
  dynamiqs/solvers/propagator.py
  dynamiqs/solvers/result.py
  dynamiqs/solvers/solver.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_propagator.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/solver_tester.py
  tests/system.py
Labels: 🚀 feature

#192 Adjoint method for Euler solver
  dynamiqs/mesolve/euler.py
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/solvers/ode/fixed_solver.py
  dynamiqs/solvers/options.py
  dynamiqs/solvers/propagator.py
  tests/mesolve/test_euler.py
Labels: 🚀 feature

#223 Argument ordering in `smesolve`
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/result.py
  dynamiqs/solvers/solver.py
Labels: 🚀 feature

#227 Minor doc fixes
  docs/getting_started/index.md
  docs/python_api/solvers.md
  docs/python_api/utils.md
  dynamiqs/utils/optimal_control.py
Labels: 📚 documentation

#230 Run tests concurrently
  pyproject.toml
Labels: 🚀 feature, 🔧 tests

#229 Add `rmax` argument to `rand_complex`
  dynamiqs/utils/optimal_control.py
Labels: 🚀 feature

#228 Rephrase `mesolve` documentation
  docs/stylesheets/extra.css
  docs/templates/python/material/docstring/admonition.html
  dynamiqs/mesolve/mesolve.py
  dynamiqs/solvers/result.py
Labels: 📚 documentation
