Repository dynamiqs/dynamiqs, pull requests merged in 2023-10, with the labels that each got.

#235 Rephrase `sesolve` documentation
  dynamiqs/sesolve/sesolve.py
Labels: 📚 documentation

#242 Add `toket`, `tobra` and `todm` utilities
  docs/python_api/navigation.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/utils/states.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/wigners.py
Labels: 🚀 feature

#238 Rephrase `smesolve` documentation
  README.md
  docs/getting_started/whatis.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/smesolve/sme_solver.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers/result.py
Labels: 📚 documentation

#236 Add generic fidelity method
  docs/python_api/navigation.md
  docs/python_api/utils.md
  dynamiqs/utils/utils.py
  tests/utils/test_utils.py
Labels: 🚀 feature

#247 Restrict to PyTorch >= 2.0
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  pyproject.toml
Labels: 🗂️ organization

#244 Add overlap and braket utility functions
  docs/python_api/navigation.md
  dynamiqs/utils/utils.py
Labels: 🚀 feature

#245 Add quadrature utilities
  docs/python_api/navigation.md
  dynamiqs/utils/operators.py
Labels: 🚀 feature

#248 Fix `smesolve` small bug on GPU
  dynamiqs/smesolve/sme_solver.py
Labels: 🐛 bug, topic: smesolve

#246 Dark namespace
  dynamiqs/__init__.py
  dynamiqs/dark/__init__.py
  dynamiqs/dark/dark.py
Labels: 🚀 feature

#239 Add first plots
  docs/python_api/navigation.md
  dynamiqs/__init__.py
  dynamiqs/plots/__init__.py
  dynamiqs/plots/misc.py
  dynamiqs/plots/utils.py
  dynamiqs/utils/tensor_types.py
Labels: 🚀 feature

#252 Add null operator
  docs/python_api/navigation.md
  dynamiqs/utils/operators.py
Labels: 🚀 feature

#258 Fix pointer for quote admonition
  docs/stylesheets/extra.css
  docs/templates/python/material/docstring/admonition.html
Labels: 📚 documentation

#262 Add SNAP gate
  docs/python_api/navigation.md
  dynamiqs/utils/optimal_control.py
Labels: 🚀 feature
