Repository dynamiqs/dynamiqs, pull requests merged in 2023-05, with the labels that each got.

#83 Add Wigner utility functions
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/ode/adaptive_ode_integrator.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/utils/__init__.py
  torchqdynamics/utils/tensor_types.py
  torchqdynamics/utils/wigner.py
Labels: 🚀 feature

#86 Refactor the `Solver` class and all subclasses
  tests/mesolve/test_adaptive.py
  tests/sesolve/test_adaptive.py
  tests/test_h_caching.py
  torchqdynamics/mesolve/adaptive.py
  torchqdynamics/mesolve/euler.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/ode/forward_solver.py
  torchqdynamics/options.py
  torchqdynamics/sesolve/adaptive.py
  torchqdynamics/sesolve/euler.py
  torchqdynamics/sesolve/propagator.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/solvers/__init__.py
  torchqdynamics/solvers/ode/__init__.py
  torchqdynamics/solvers/ode/adaptive_integrator.py
  torchqdynamics/solvers/ode/adaptive_solver.py
  torchqdynamics/solvers/ode/forward_solver.py
  torchqdynamics/solvers/propagator.py
  torchqdynamics/solvers/solver.py
Labels: 🗂️ organization

#91 Fix tqdm warning for adaptive solvers
  torchqdynamics/solvers/ode/adaptive_solver.py
Labels: 🐛 bug, topic: ode

#93 Move gradient algorithm parametrisation to solver options
  tests/mesolve/mesolver_tester.py
  tests/test_h_caching.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/options.py
  torchqdynamics/options.py
  torchqdynamics/sesolve/options.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/solvers/ode/forward_solver.py
  torchqdynamics/solvers/solver.py
Labels: 🗂️ organization

#94 No autograd in base solver
  torchqdynamics/options.py
  torchqdynamics/solvers/ode/adaptive_solver.py
  torchqdynamics/solvers/ode/forward_solver.py
  torchqdynamics/solvers/propagator.py
  torchqdynamics/solvers/solver.py
Labels: 🗂️ organization

#89 Handle batching for time-dependent Hamiltonians
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/solvers/solver.py
  torchqdynamics/tensor_formatter.py
  torchqdynamics/utils/tensor_types.py
Labels: 🚀 feature

#95 Add documentation website using mkdocs
  .gitignore
  CONTRIBUTING.md
  docs/getting_started/first_steps.md
  docs/getting_started/index.md
  docs/getting_started/installation.md
  docs/index.md
  docs/javascripts/mathjax.js
  docs/reference/foo.md
  docs/reference/index.md
  docs/tutorials/ecd.md
  docs/tutorials/index.md
  docs/tutorials/optimal_control.md
  docs/tutorials/snap.md
  mkdocs.yml
  pyproject.toml
Labels: 📚 documentation

#96 Move tensor_formatter to utils folder
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/utils/tensor_formatter.py
Labels: 🗂️ organization

#98 Rename `batch_...` to `format...` for `TensorFormatter` methods that also handle conversion
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/utils/tensor_formatter.py
Labels: 🗂️ organization

#97 Add TDTensor class
  tests/utils/test_h_caching.py
  torchqdynamics/mesolve/mesolve.py
  torchqdynamics/mesolve/rouchon.py
  torchqdynamics/sesolve/sesolve.py
  torchqdynamics/solvers/solver.py
  torchqdynamics/utils/td_tensor.py
  torchqdynamics/utils/tensor_formatter.py
  torchqdynamics/utils/tensor_types.py
Labels: 🚀 feature

#108 Doc utils
  docs/javascripts/mathjax.js
  docs/reference/foo.md
  docs/reference/utils/utils.md
  docs/templates/python/material/docstring/parameters.html
  docs/templates/python/material/docstring/returns.html
  mkdocs.yml
  pyproject.toml
  torchqdynamics/utils/utils.py
Labels: 📚 documentation

#109 Doc dark mode
  mkdocs.yml
Labels: 📚 documentation

#113 New logo
  .pre-commit-config.yaml
  README.md
  media/dynamiqs_logo.png
Labels: 🚀 feature

#111 Fix typing confusion between float and 1-element tensors and remove arguments count check for `CallableTDTensor`
  dynamiqs/solvers/ode/adaptive_integrator.py
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/ode/forward_solver.py
  dynamiqs/solvers/propagator.py
  dynamiqs/solvers/solver.py
  dynamiqs/utils/td_tensor.py
Labels: 🐛 bug

#119 Begin CSS of doc
  docs/reference/utils/utils.md
  docs/stylesheets/extra.css
Labels: 🚀 feature

#123 Fix design issue with `AdaptiveSolver`
  dynamiqs/mesolve/adaptive.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/adaptive.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solvers/ode/adaptive_integrator.py
  dynamiqs/solvers/ode/adaptive_solver.py
Labels: 🗂️ organization, topic: ode

#126 Fix adjoint gradients from exp_ops
  dynamiqs/solvers/ode/fixed_solver.py
Labels: 🐛 bug
