Repository dynamiqs/dynamiqs, pull requests merged in 2023-06, with the labels that each got.

#133 Caching tensors
  dynamiqs/mesolve/me_solver.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/sesolve/propagator.py
  dynamiqs/solvers/solver.py
  dynamiqs/utils/solver_utils.py
  dynamiqs/utils/td_tensor.py
  pyproject.toml
  tests/mesolve/me_solver_tester.py
  tests/mesolve/open_system.py
  tests/utils/test_h_caching.py
Labels: 🚀 feature

#136 Remove `FixedSolver` forward and backward methods useless `dt` argument
  dynamiqs/mesolve/euler.py
  dynamiqs/mesolve/rouchon.py
  dynamiqs/sesolve/euler.py
  dynamiqs/solvers/ode/fixed_solver.py
Labels: 🗂️ organization

#137 Add tests for adjoint through `exp_ops`
  dynamiqs/solvers/ode/fixed_solver.py
  tests/mesolve/me_solver_tester.py
  tests/mesolve/test_rouchon.py
Labels: 🔧 tests

#140 Minor fixes
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
Labels: 🐛 bug

#143 Small fix to run code on GPUs
  dynamiqs/solvers/ode/adaptive_solver.py
  dynamiqs/solvers/propagator.py
  tests/conftest.py
Labels: 🐛 bug

#144 Fix adjoint method when `exp_ops=None`
  dynamiqs/solvers/ode/fixed_solver.py
Labels: 🐛 bug

#142 Move `dtype` and `device` to `options`
  dynamiqs/mesolve/mesolve.py
  dynamiqs/options.py
  dynamiqs/sesolve/sesolve.py
Labels: 🗂️ organization

#146 Performance and notation improvements for the adaptive solver
  dynamiqs/options.py
  dynamiqs/solvers/ode/adaptive_solver.py
Labels: 🚀 feature
