Repository dynamiqs/dynamiqs, pull requests merged in 2024-09, with the labels that each got.

#680 Add sparse DIA constructor
  dynamiqs/qarrays/types.py
  dynamiqs/utils/operators.py
Labels: feature, 🫴🏼 utils

#684 Add pow, powm and tests
  dynamiqs/qarrays/sparse_dia_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
Labels: feature, 🔧 technical

#688 Fix docserve warnings
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/utils/states.py
Labels: bug, 📚 documentation

#687 Introduce global settings file
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/layout.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_dia_qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/global_settings.py
  dynamiqs/utils/operators.py
  mkdocs.yml
Labels: feature, 🔧 technical

#690 Fix ruff
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/utils.py
Labels: bug, 🔧 technical

#692 Fix sum and squeeze to return `Array` or `QArray` depending on axis
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
Labels: bug, 🔧 technical

#685 Fix performance of `mesolve` with QArrays
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_dia_qarray.py
Labels: performance, 🌀 solvers

#691 Refactor how `final_state` and `final_propagator` are saved
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/result.py
  tests/sepropagator/test_sepropagator.py
Labels: bug, 🌀 solvers

#695 Merge main into dev qarray
  docs/templates/python/material/attribute.html
  docs/templates/python/material/class.html
  docs/templates/python/material/class.html.jinja
  docs/templates/python/material/docstring/admonition.html
  docs/templates/python/material/docstring/admonition.html.jinja
  docs/templates/python/material/docstring/attributes.html
  docs/templates/python/material/docstring/attributes.html.jinja
  docs/templates/python/material/docstring/examples.html.jinja
  docs/templates/python/material/docstring/functions.html
  docs/templates/python/material/docstring/functions.html.jinja
  docs/templates/python/material/docstring/parameters.html
  docs/templates/python/material/docstring/parameters.html.jinja
  docs/templates/python/material/docstring/raises.html
  docs/templates/python/material/docstring/raises.html.jinja
  docs/templates/python/material/docstring/returns.html
  docs/templates/python/material/docstring/returns.html.jinja
  docs/templates/python/material/function.html
  docs/templates/python/material/function.html.jinja
  docs/templates/python/material/labels.html
  docs/templates/python/material/module.html.jinja
  docs/templates/python/material/table.html
  docs/templates/python/material/table.html.jinja
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/result.py
  tests/sepropagator/test_sepropagator.py
Labels: organisation, 🔧 technical

#702 Add .block_until_ready() method to Result
  dynamiqs/result.py
Labels: feature, ⏱️ benchmarks

#703 Prepare `v0.2.0` release
  README.md
  docs/documentation/getting_started/installation.md
  dynamiqs/__init__.py
  pyproject.toml
Labels: organisation, 🪛 tooling

#705 Fix Python API table by adding systematic members
  docs/python_api/index.md
  pyproject.toml
Labels: bug, 📚 documentation

#706 Fix CI following Sybil v7 with upgrade to Pytest v8
  docs/conftest.py
  dynamiqs/conftest.py
  pyproject.toml
Labels: bug, 🎯 tests

#697 Capitalize the library name: `dynamiqs` -> `Dynamiqs`
  CONTRIBUTING.md
  LICENSE
  README.md
  docs/community/citing.md
  docs/community/contributing.md
  docs/community/index.md
  docs/documentation/basics/batching-simulations.md
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/documentation/basics/time-dependent-operators.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/examples.md
  docs/documentation/getting_started/installation.md
  docs/documentation/getting_started/sharp-bits.md
  docs/documentation/getting_started/whatis.md
  docs/documentation/index.md
  docs/media/dynamiqs-logo-large.png
  docs/media/dynamiqs-logo.png
  docs/media/logo-typeface-darktype.png
  docs/media/logo-typeface-lighttype.png
  docs/overrides/home.html
  docs/python_api/index.md
  docs/stylesheets/extra.css
  docs/stylesheets/theme.css
  dynamiqs/integrators/_utils.py
  dynamiqs/plot/utils.py
  dynamiqs/random.py
  dynamiqs/time_array.py
  mkdocs.yml
  tests/utils/test_utils.py
Labels: 📚 documentation, organisation

#709 Temporary fix jax version for the CI
  pyproject.toml
Labels: bug, 🔧 technical

#710 Improve gradient example
  README.md
  docs/documentation/getting_started/examples.md
Labels: 📚 documentation, feature

#698 Fix license date
  LICENSE
  mkdocs.yml
Labels: 📚 documentation, organisation

#708 Change default plots font to sans serif
  dynamiqs/plot/utils.py
Labels: feature, 🎨 plot

#700 Fix tests due to new layout argument
  tests/mepropagator/test_expm.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_expm.py
  tests/mesolve/test_rouchon.py
  tests/sepropagator/test_sepropagator.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_expm.py
  tests/utils/test_operators.py
Labels: bug, 🎯 tests

#699 Simplify save logic
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/mepropagator/expm_integrator.py
  dynamiqs/integrators/mesolve/expm_integrator.py
  dynamiqs/integrators/sepropagator/expm_integrator.py
  dynamiqs/integrators/sesolve/expm_integrator.py
  dynamiqs/options.py
  dynamiqs/result.py
Labels: feature, 🌀 solvers

#714 Support double precision wigner computation on GPU
  dynamiqs/utils/quantum_utils/wigner.py
Labels: feature, 🫴🏼 utils

#716 Partial support for QuTiP >= 5.0
  dynamiqs/utils/jax_utils.py
  pyproject.toml
  tests/utils/test_utils.py
Labels: bug, 🔧 technical

#717 Fix JAX version compatibility with latest equinox
  pyproject.toml
Labels: bug, 🔧 technical

#718 Specify how to find default gradient in documentation
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/solver.py
Labels: 📚 documentation, feature

#548 Add `dq.smesolve()`
  docs/glossary.md
  docs/python_api/index.md
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/smesolve/diffrax_integrator.py
  dynamiqs/result.py
  dynamiqs/solver.py
  mkdocs.yml
Labels: feature, 🌀 solvers

#696 Simplify `QArray` repr with `layout` property
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/layout.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_dia_qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/time_array.py
  dynamiqs/utils/global_settings.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/states.py
Labels: feature, 🔧 technical

#701 Fix documentation
  README.md
  docs/documentation/basics/batching-simulations.md
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/documentation/getting_started/examples.md
  dynamiqs/options.py
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/wigner.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/result.py
  dynamiqs/time_array.py
  dynamiqs/utils/quantum_utils/general.py
  tests/mesolve/test_batching.py
  tests/sesolve/test_batching.py
  tests/utils/test_states.py
  tests/utils/test_utils.py
Labels: bug, 📚 documentation

#721 Bump version to `v0.2.1`
  dynamiqs/__init__.py
Labels: organisation, 🪛 tooling

#723 Improve GIFs creation performance and fix the color quantization bug
  docs/conftest.py
  docs/hooks.py
  dynamiqs/conftest.py
  dynamiqs/plot/utils.py
  dynamiqs/plot/wigner.py
  pyproject.toml
Labels: performance, 🫴🏼 utils

#726 Move ptrace tuple args to *args
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_dia_qarray.py
Labels: feature, 🫴🏼 utils

#724 Refactor integrators
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/integrators/mepropagator/expm_integrator.py
  dynamiqs/integrators/mesolve/diffrax_integrator.py
  dynamiqs/integrators/mesolve/expm_integrator.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
  dynamiqs/integrators/sepropagator/diffrax_integrator.py
  dynamiqs/integrators/sepropagator/expm_integrator.py
  dynamiqs/integrators/sesolve/diffrax_integrator.py
  dynamiqs/integrators/sesolve/expm_integrator.py
Labels: organisation, 🔧 technical

#727 Better documentation example
  README.md
  README_PYPI.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/examples.md
  dynamiqs/result.py
Labels: 📚 documentation, feature

#729 Remove dag section from sharp bits
  docs/documentation/getting_started/sharp-bits.md
Labels: 📚 documentation, feature

#728 Improve tutorials reading flow
  docs/documentation/basics/time-dependent-operators.md
  docs/documentation/getting_started/sharp-bits.md
Labels: 📚 documentation, feature

#730 Merge main into dev-qarray
  README.md
  README_PYPI.md
  docs/conftest.py
  docs/documentation/basics/time-dependent-operators.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/examples.md
  docs/documentation/getting_started/sharp-bits.md
  docs/hooks.py
  dynamiqs/__init__.py
  dynamiqs/conftest.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/integrators/mepropagator/expm_integrator.py
  dynamiqs/integrators/mesolve/diffrax_integrator.py
  dynamiqs/integrators/mesolve/expm_integrator.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
  dynamiqs/integrators/sepropagator/diffrax_integrator.py
  dynamiqs/integrators/sepropagator/expm_integrator.py
  dynamiqs/integrators/sesolve/diffrax_integrator.py
  dynamiqs/integrators/sesolve/expm_integrator.py
  dynamiqs/plot/utils.py
  dynamiqs/plot/wigner.py
  dynamiqs/result.py
  pyproject.toml
Labels: organisation, 🔧 technical

#731 Fix ptrace test
  tests/qarrays/test_dense_qarray.py
Labels: bug, 🎯 tests

#735 Add CNOT gate
  docs/python_api/index.md
  dynamiqs/utils/operators.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#732 Filter user warnings in tests when expected
  tests/qarrays/test_sparse_dia_qarray.py
Labels: feature, 🎯 tests

#725 Fix delayed imports by refactoring qarrays/ folder
  dynamiqs/_checks.py
  dynamiqs/dark/dark.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/wigner.py
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/type_conversion.py
  dynamiqs/qarrays/types.py
  dynamiqs/qarrays/utils.py
  dynamiqs/random.py
  dynamiqs/result.py
  dynamiqs/time_array.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/quantum_utils/wigner.py
  dynamiqs/utils/states.py
  dynamiqs/utils/vectorization.py
  tests/integrator_tester.py
  tests/qarrays/test_sparse_dia_qarray.py
  tests/qarrays/test_utils.py
  tests/test_time_array.py
  tests/utils/test_operators.py
  tests/utils/test_utils.py
Labels: feature, organisation
