Repository dynamiqs/dynamiqs, pull requests merged in 2024-10, with the labels that each got.

#737 Add method to get bloch sphere coordinates of a ket or a density matrix
  docs/python_api/index.md
  dynamiqs/_checks.py
  dynamiqs/utils/quantum_utils/__init__.py
  dynamiqs/utils/quantum_utils/general.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#739 Fix equinox warning on Equinox >= 0.11.6
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: bug, 🔧 technical

#740 Generalize `dq.number()` to multi-modes
  dynamiqs/utils/operators.py
Labels: feature, 🫴🏼 utils

#749 Add an index argument to dq.set_device
  dynamiqs/utils/jax_utils.py
Labels: feature, 🫴🏼 utils

#750 Disallow jax 0.4.34
  pyproject.toml
Labels: bug, 🪛 tooling

#743 Adapt task doctest to different OS
  docs/remove_files.py
  pyproject.toml
Labels: bug, 🪛 tooling

#736 Minor nits on top of qarray types refactoring
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
Labels: bug, 🔧 technical

#754 Turn on the CI for PRs targetting `dev-qarray` branch
  .github/workflows/ci.yml
  docs/documentation/basics/time-dependent-operators.md
  docs/documentation/getting_started/sharp-bits.md
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/type_conversion.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/vectorization.py
Labels: organisation, 🪛 tooling

#752 Fix task removing figures
  docs/remove_figs.py
  docs/remove_files.py
  pyproject.toml
Labels: bug, 🪛 tooling

#755 Disallow mkdocstrings-python=1.12.0 due to bug parsing strings in signatures
  pyproject.toml
Labels: bug, 📚 documentation

#707 Setup doc versionning
  .github/workflows/publish-doc.yml
  docs/overrides/home.html
  docs/overrides/main.html
  docs/overrides/partials/header.html
  docs/stylesheets/extra.css
  docs/stylesheets/home.css
  docs/stylesheets/theme.css
  docs/templates/python/material/table.html.jinja
  mkdocs.yml
  pyproject.toml
Labels: 📚 documentation, feature

#757 Fix publish doc CI for mike
  .github/workflows/publish-doc.yml
Labels: bug, 📚 documentation

#758 Re-fix publish doc CI for mike
  .github/workflows/publish-doc.yml
Labels: bug, 📚 documentation

#759 Merge main into dev-qarray
  .github/workflows/publish-doc.yml
  docs/media/favicon.png
  docs/media/favicon.svg
  docs/media/logo-dark-large.png
  docs/media/logo-dark.png
  docs/media/logo-inverted-large.png
  docs/media/logo-inverted.png
  docs/media/logo-large.png
  docs/media/logo-typeface-darktype.png
  docs/media/logo-typeface-lighttype.png
  docs/media/logo-white-large.png
  docs/media/logo-white.png
  docs/media/logo.png
  docs/overrides/home.html
  docs/overrides/main.html
  docs/overrides/partials/header.html
  docs/remove_figs.py
  docs/stylesheets/extra.css
  docs/stylesheets/home.css
  docs/stylesheets/theme.css
  docs/templates/python/material/table.html.jinja
  mkdocs.yml
  pyproject.toml
Labels: organisation, 🔧 technical

#760 Add workflow to automatically publish dev-qarray doc
  .github/workflows/publish-doc-dev-qarray.yml
Labels: organisation, 🪛 tooling

#763 Fix broken links in homepage
  docs/overrides/home.html
Labels: bug, 📚 documentation

#761 Fix colorbar rendering under constrained_layout
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/utils.py
Labels: bug, 🎨 plot

#762 Fix documentation figures rendering
  docs/documentation/basics/workflow.md
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/misc.py
  dynamiqs/plot/utils.py
  dynamiqs/plot/wigner.py
  dynamiqs/random.py
Labels: bug, 📚 documentation

#764 Support empty jump ops list in `lindbladian` and `slindbladian`
  dynamiqs/_checks.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/vectorization.py
Labels: feature, 🫴🏼 utils

#765 Update version `v0.2.1` -> `v0.2.2`
  dynamiqs/__init__.py
Labels: organisation, 🪛 tooling

#766 Add workflow to automatically publish dev-smesolve doc
  .github/workflows/publish-doc-dev-smesolve.yml
Labels: organisation, 🪛 tooling

#767 Turn on CI on PRs targetting `dev-smesolve`
  .github/workflows/ci.yml
Labels: organisation, 🪛 tooling

#742 Vectorize Rx, Ry and Rz gates
  dynamiqs/utils/operators.py
Labels: feature, 🫴🏼 utils

#769 Fix implementation
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/integrators/smesolve/diffrax_integrator.py
  dynamiqs/result.py
  dynamiqs/solver.py
Labels: bug, 🌀 solvers

#770 Rename API `smesolve` -> `dsmesolve`
  docs/python_api/index.md
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/integrators/dsmesolve/__init__.py
  dynamiqs/integrators/dsmesolve/diffrax_integrator.py
  dynamiqs/integrators/smesolve/diffrax_integrator.py
  dynamiqs/result.py
  mkdocs.yml
Labels: organisation, 🌀 solvers

#771 Fix minor typo
  dynamiqs/integrators/core/save_mixin.py
Labels: bug, 🌀 solvers

#774 Remove `tmeas` from `dsmesolve` API
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/result.py
Labels: organisation, 🌀 solvers

#775 Replace Diffrax solvers by homemade solver for the SME
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/integrators/dsmesolve/diffrax_integrator.py
  dynamiqs/integrators/dsmesolve/fixed_step_integrator.py
Labels: organisation, 🌀 solvers

#776 Various small documentation fixes related to `dsmesolve()`
  README.md
  README_PYPI.md
  docs/python_api/index.md
  dynamiqs/result.py
  dynamiqs/solver.py
  mkdocs.yml
Labels: bug, 📚 documentation

#777 More fixes to `dsmesolve` homemade solver and documentation
  docs/documentation/getting_started/whatis.md
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/integrators/dsmesolve/fixed_step_integrator.py
  dynamiqs/result.py
  dynamiqs/solver.py
Labels: bug, 🌀 solvers

#773 Remove `FutureWarning` filter
  dynamiqs/integrators/core/diffrax_integrator.py
Labels: organisation, 🔧 technical

#779 Add draft diffusive sme advanced examples
  docs/documentation/advanced_examples/monitored-oscillator.md
  docs/documentation/advanced_examples/monitored-qubit.md
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/dsmesolve/fixed_step_integrator.py
  mkdocs.yml
Labels: 📚 documentation, feature

#780 Fix figure links to relative for mike
  docs/documentation/advanced_examples/monitored-oscillator.md
  docs/documentation/advanced_examples/monitored-qubit.md
Labels: bug, 📚 documentation

#782 Fix gradient example analytical expression for alpha(t)
  README.md
  README_PYPI.md
  docs/documentation/getting_started/examples.md
Labels: bug, 📚 documentation

#778 Simplify implementation of vectorization utilities
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
Labels: feature, 🔧 technical

#781 Helper for `jump_ops` stacking in ME integrators
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
Labels: organisation, 🌀 solvers

#783 Simplify and document cartesian/non-cartesian vectorisation
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/time_array.py
Labels: feature, 🔧 technical

#746 Add an example tutorial on the Kerr oscillator
  docs/documentation/advanced_examples/kerr-oscillator.md
  docs/documentation/index.md
  mkdocs.yml
  pyproject.toml
Labels: 📚 documentation, feature

#784 Fix links in Kerr tutorial
  docs/documentation/advanced_examples/kerr-oscillator.md
Labels: bug, 📚 documentation
