Repository dynamiqs/dynamiqs, pull requests merged in 2024-11, with the labels that each got.

#787 Introduce a See Also admonition
  docs/stylesheets/extra.css
  docs/stylesheets/theme.css
  dynamiqs/utils/vectorization.py
  mkdocs.yml
Labels: 📚 documentation, feature

#681 Add `floquet`
  docs/python_api/index.md
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/floquet/__init__.py
  dynamiqs/integrators/floquet/floquet_integrator.py
  dynamiqs/result.py
  mkdocs.yml
  tests/floquet/__init__.py
  tests/floquet/floquet_qubit.py
  tests/floquet/test_adaptive.py
  tests/floquet/test_batching.py
Labels: feature, 🌀 solvers

#789 Merge main into dev-qarray
  README.md
  README_PYPI.md
  docs/documentation/advanced_examples/kerr-oscillator.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/examples.md
  docs/documentation/index.md
  docs/overrides/home.html
  docs/python_api/index.md
  docs/stylesheets/extra.css
  docs/stylesheets/theme.css
  dynamiqs/__init__.py
  dynamiqs/_checks.py
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/floquet/__init__.py
  dynamiqs/integrators/floquet/floquet_integrator.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/misc.py
  dynamiqs/plot/utils.py
  dynamiqs/plot/wigner.py
  dynamiqs/random.py
  dynamiqs/result.py
  dynamiqs/time_array.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/vectorization.py
  mkdocs.yml
  pyproject.toml
  tests/floquet/__init__.py
  tests/floquet/floquet_qubit.py
  tests/floquet/test_adaptive.py
  tests/floquet/test_batching.py
  tests/sesolve/test_batching.py
  tests/test_time_array.py
Labels: organisation, 🔧 technical

#790 Temporary fix for jaxtyping drop of support for Python 3.9
  pyproject.toml
Labels: bug, 🔧 technical

#788 Minor fixes to the "See also" admonitions
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/vectorization.py
  pyproject.toml
Labels: bug, 📚 documentation

#795 Fix various broken links
  README.md
  README_PYPI.md
  dynamiqs/integrators/_utils.py
Labels: bug, 📚 documentation

#794 Update the API of conversion utilities
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/wigner.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/layout.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/type_conversion.py
  dynamiqs/random.py
  dynamiqs/result.py
  dynamiqs/utils/global_settings.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/quantum_utils/wigner.py
  dynamiqs/utils/states.py
  tests/integrator_tester.py
  tests/qarrays/test_sparse_dia_qarray.py
  tests/qarrays/test_utils.py
  tests/test_time_array.py
  tests/utils/test_operators.py
  tests/utils/test_utils.py
Labels: feature, 🫴🏼 utils

#793 Improve contributing documentation
  CONTRIBUTING.md
  docs/community/contributing.md
Labels: 📚 documentation, feature

#796 Merge main into dev-smesolve
  CONTRIBUTING.md
  README.md
  README_PYPI.md
  docs/community/citing.md
  docs/community/contributing.md
  docs/documentation/advanced_examples/kerr-oscillator.md
  docs/documentation/getting_started/examples.md
  docs/documentation/index.md
  docs/python_api/index.md
  docs/stylesheets/extra.css
  docs/stylesheets/theme.css
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/floquet/__init__.py
  dynamiqs/integrators/floquet/floquet_integrator.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
  dynamiqs/result.py
  dynamiqs/time_array.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/vectorization.py
  mkdocs.yml
  pyproject.toml
  tests/floquet/__init__.py
  tests/floquet/floquet_qubit.py
  tests/floquet/test_adaptive.py
  tests/floquet/test_batching.py
Labels: organisation, 🔧 technical

#797 Various fixes following merge
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/dsmesolve/fixed_step_integrator.py
Labels: organisation, 🔧 technical

#800 Fix license
  LICENSE
  NOTICE
Labels: bug, 🪛 tooling

#798 Document conversion functions
  docs/documentation/basics/batching-simulations.md
  docs/documentation/basics/closed-systems.md
  docs/glossary.md
  docs/python_api/index.md
  dynamiqs/conftest.py
  dynamiqs/dark/dark.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/wigner.py
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/type_conversion.py
  dynamiqs/qarrays/utils.py
  dynamiqs/result.py
  dynamiqs/time_array.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/quantum_utils/wigner.py
  dynamiqs/utils/states.py
  dynamiqs/utils/vectorization.py
  mkdocs.yml
Labels: 📚 documentation, feature

#801 Fix dtypes in QArrays
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/time_array.py
  dynamiqs/utils/quantum_utils/general.py
Labels: bug, 🔧 technical

#803 Use qarrays in `random.py`
  docs/python_api/index.md
  dynamiqs/random.py
  mkdocs.yml
Labels: organisation, 🫴🏼 utils

#807 Fix bug when summing with an zero sparse qarray
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: bug, 🔧 technical

#810 Fix ruff release v0.8.0
  dynamiqs/integrators/__init__.py
  dynamiqs/plot/__init__.py
  dynamiqs/plot/wigner.py
  dynamiqs/random.py
  dynamiqs/result.py
  dynamiqs/solver.py
  dynamiqs/time_array.py
  dynamiqs/utils/jax_utils.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/quantum_utils/__init__.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/states.py
  dynamiqs/utils/vectorization.py
  pyproject.toml
Labels: bug, 🎯 tests

#809 Update README
  README.md
  README_PYPI.md
  docs/documentation/getting_started/whatis.md
Labels: 📚 documentation, feature

#808 Fix JIT compatibility with state creation
  dynamiqs/utils/states.py
Labels: bug, 🫴🏼 utils

#811 Merge main into dev-qarray
  CONTRIBUTING.md
  LICENSE
  NOTICE
  README.md
  README_PYPI.md
  docs/community/citing.md
  docs/community/contributing.md
  docs/documentation/getting_started/whatis.md
  dynamiqs/_utils.py
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/plot/__init__.py
  dynamiqs/plot/wigner.py
  dynamiqs/qarrays/utils.py
  dynamiqs/random.py
  dynamiqs/result.py
  dynamiqs/solver.py
  dynamiqs/time_array.py
  dynamiqs/utils/global_settings.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/quantum_utils/__init__.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/states.py
  dynamiqs/utils/vectorization.py
  pyproject.toml
Labels: organisation, 🔧 technical

#812 Fix bug when summing with an zero sparse qarray
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: bug, 🔧 technical

#804 Nested conversions
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/utils.py
  pyproject.toml
  tests/qarrays/test_utils.py
Labels: feature, 🔧 technical

#802 Document qarray
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/qarrays/qarray.py
  mkdocs.yml
Labels: 📚 documentation, feature
