Repository dynamiqs/dynamiqs, pull requests merged in 2024-07, with the labels that each got.

#622 Rename `SparseQArray` to `SparseDIAQArray`
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/sparse_dia_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
Labels: 🔧 technical, 🫴🏼 utils

#623 Start integrating QArray into utils
  dynamiqs/_checks.py
  dynamiqs/_utils.py
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/types.py
  dynamiqs/utils/utils/general.py
  dynamiqs/utils/vectorization.py
Labels: feature, 🔧 technical

#624 New `QArray` and `DenseQArray` string `__repr__`
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
Labels: feature, 🔧 technical

#625 Integrate `QArray` in creation utils
  dynamiqs/dark/dark.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/types.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/states.py
Labels: feature, 🔧 technical

#626 Fix docstrings utils with new `QArray` string `__repr__`
  dynamiqs/utils/jax_utils.py
  dynamiqs/utils/utils/general.py
Labels: 📚 documentation, feature

#627 Filter FutureWarning: unhashable type
  dynamiqs/core/diffrax_solver.py
Labels: bug, 🔧 technical

#634 Fix broken links in homepage
  docs/overrides/home.html
Labels: bug, 📚 documentation

#628 Add Kronecker Product support to sparse dia qarrays
  dynamiqs/qarrays/sparse_dia_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
Labels: feature, 🔧 technical

#620 Start integrating `QArray` into `sesolve` and `mesolve`
  dynamiqs/core/_utils.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_dia_qarray.py
  dynamiqs/sesolve/sesolve.py
Labels: feature, 🔧 technical

#636 Codebase restructuration
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/__init__.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/integrators/core/__init__.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/propagator_integrator.py
  dynamiqs/integrators/mesolve/__init__.py
  dynamiqs/integrators/mesolve/diffrax_integrator.py
  dynamiqs/integrators/mesolve/propagator_integrator.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
  dynamiqs/integrators/sesolve/__init__.py
  dynamiqs/integrators/sesolve/diffrax_integrator.py
  dynamiqs/integrators/sesolve/propagator_integrator.py
  dynamiqs/integrators/smesolve/__init__.py
  dynamiqs/mesolve/__init__.py
  dynamiqs/mesolve/mepropagator.py
  dynamiqs/sesolve/__init__.py
  dynamiqs/sesolve/sediffrax.py
  dynamiqs/smesolve/__init__.py
  dynamiqs/solvers.py
  mkdocs.yml
Labels: organisation, 🔧 technical

#635 Fix typings in various files to migrate
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/propagator_solver.py
  dynamiqs/mesolve/mepropagator.py
  dynamiqs/result.py
  dynamiqs/sesolve/sepropagator.py
  dynamiqs/smesolve/smesolve.py
Labels: feature, 🔧 technical

#638 Rename classes in tests
  tests/integrator_tester.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_propagator.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
Labels: organisation, 🔧 technical

#640 Various minor nits (fix some typing and imports)
  dynamiqs/_utils.py
  dynamiqs/solver.py
  dynamiqs/utils/jax_utils.py
  pyproject.toml
Labels: organisation, 🔧 technical

#639 Implement `dq.stack` for QArrays and fix mesolve `vector_field` consequently
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/sparse_dia_qarray.py
  dynamiqs/qarrays/utils.py
  mkdocs.yml
Labels: feature, 🔧 technical

#637 Add `sepropagator` solver
  docs/documentation/basics/closed-systems.md
  docs/python_api/index.md
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/sepropagator/__init__.py
  dynamiqs/integrators/sepropagator/dynamiqs_integrator.py
  dynamiqs/integrators/sepropagator/expm_integrator.py
  dynamiqs/result.py
  dynamiqs/solver.py
  mkdocs.yml
  tests/sepropagator/__init__.py
  tests/sepropagator/test_sepropagator.py
Labels: feature, 🌀 solvers

#631 Convert TimeArray to QArrays
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/types.py
  dynamiqs/time_array.py
Labels: feature, 🔧 technical

#648 Update vector field in mesolve
  dynamiqs/integrators/mesolve/diffrax_integrator.py
Labels: feature, 🌀 solvers

#643 Improve `sepropagator`
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/sepropagator/diffrax_integrator.py
  dynamiqs/integrators/sepropagator/dynamiqs_integrator.py
  dynamiqs/integrators/sepropagator/expm_integrator.py
  tests/sepropagator/test_sepropagator.py
Labels: organisation, 🌀 solvers

#649 Various minor documentation nits
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/utils/states.py
Labels: 📚 documentation, feature

#519 Add gifit function
  docs/python_api/index.md
  dynamiqs/plots/__init__.py
  dynamiqs/plots/utils.py
  mkdocs.yml
Labels: feature, 🎨 plot

#655 Fix kronecker_dia
  dynamiqs/qarrays/sparse_dia_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
Labels: bug, 🔧 technical

#656 Add test for out-of-bounds non-zero values in SparseDIA initialization
  tests/qarrays/test_sparse_dia_qarray.py
Labels: feature, 🔧 technical

#659 Fix typing in test
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
Labels: bug, 🎯 tests
