Repository dynamiqs/dynamiqs, pull requests merged in 2024-08, with the labels that each got.

#660 Clean up SparseDIAQArray
  dynamiqs/_utils.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_dia_qarray.py
  dynamiqs/qarrays/types.py
  dynamiqs/qarrays/utils.py
  dynamiqs/time_array.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/matrix_format_selector.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/states.py
  dynamiqs/utils/utils/general.py
  dynamiqs/utils/vectorization.py
  pyproject.toml
  tests/mesolve/open_system.py
  tests/mesolve/test_propagator.py
  tests/qarrays/test_sparse_dia_qarray.py
  tests/qarrays/test_utils.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_propagator.py
  tests/utils/test_operators_dispatch.py
Labels: feature, 🔧 technical

#663 Small fixes for sparse QArrays
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_dia_qarray.py
Labels: bug, 🔧 technical

#664 Move rand_* to dq.rand.*
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/plots/plots_hinton.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/rand.py
  mkdocs.yml
  tests/mesolve/test_batching.py
  tests/sepropagator/test_sepropagator.py
  tests/sesolve/test_batching.py
  tests/utils/test_utils.py
Labels: organisation, 🫴🏼 utils

#665 Get pwc or modulated time array prefactor value
  dynamiqs/time_array.py
Labels: feature, 🫴🏼 utils

#668 Move `dq.plot_*` to `dq.plot.*`
  docs/conftest.py
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/conftest.py
  dynamiqs/plot/__init__.py
  dynamiqs/plot/colormaps.py
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/misc.py
  dynamiqs/plot/utils.py
  dynamiqs/plot/wigner.py
  dynamiqs/plots/__init__.py
  dynamiqs/random.py
  mkdocs.yml
Labels: organisation, 🎨 plot

#667 Rename `dq.rand` namespace to `dq.random` and reorganise files
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/plots/plots_hinton.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/random.py
  dynamiqs/utils/__init__.py
  mkdocs.yml
  tests/mesolve/test_batching.py
  tests/sepropagator/test_sepropagator.py
  tests/sesolve/test_batching.py
  tests/utils/test_utils.py
Labels: organisation, 🫴🏼 utils

#670 Move `dq.plot_*` to `dq.plot.*`
  docs/conftest.py
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/conftest.py
  dynamiqs/plot/__init__.py
  dynamiqs/plot/colormaps.py
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/plot/misc.py
  dynamiqs/plot/utils.py
  dynamiqs/plot/wigner.py
  dynamiqs/plots/__init__.py
  dynamiqs/random.py
  mkdocs.yml
  tests/test_plot.py
Labels: organisation, 🎨 plot

#671 Add random namespace to `dq.*`
  dynamiqs/__init__.py
Labels: bug, 🫴🏼 utils

#661 Consolidate `Expm` solver, introduce `mepropagator`
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/python_api/index.md
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/propagator_integrator.py
  dynamiqs/integrators/mepropagator/__init__.py
  dynamiqs/integrators/mepropagator/expm_integrator.py
  dynamiqs/integrators/mesolve/diffrax_integrator.py
  dynamiqs/integrators/mesolve/expm_integrator.py
  dynamiqs/integrators/mesolve/propagator_integrator.py
  dynamiqs/integrators/sepropagator/diffrax_integrator.py
  dynamiqs/integrators/sepropagator/expm_integrator.py
  dynamiqs/integrators/sesolve/diffrax_integrator.py
  dynamiqs/integrators/sesolve/expm_integrator.py
  dynamiqs/integrators/sesolve/propagator_integrator.py
  dynamiqs/result.py
  dynamiqs/solver.py
  mkdocs.yml
  tests/mepropagator/__init__.py
  tests/mepropagator/mepropagator_utils.py
  tests/mepropagator/test_batching.py
  tests/mepropagator/test_expm.py
  tests/mesolve/test_expm.py
  tests/mesolve/test_propagator.py
  tests/sesolve/test_expm.py
  tests/sesolve/test_propagator.py
Labels: feature, 🌀 solvers

#674 Fix ruff (noqa for non-ascii character in import statement)
  dynamiqs/qarrays/qarray.py
Labels: bug, 🪛 tooling

#673 Nits fight back
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/time_array.py
  dynamiqs/utils/quantum_utils/general.py
  dynamiqs/utils/quantum_utils/wigner.py
  dynamiqs/utils/vectorization.py
  tests/mesolve/open_system.py
  tests/mesolve/test_batching.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_batching.py
  tests/system.py
  tests/test_plot.py
Labels: organisation, 🔧 technical

#675 Fix some of the doctests
  dynamiqs/plot/fock.py
  dynamiqs/plot/hinton.py
  dynamiqs/qarrays/sparse_dia_qarray.py
  dynamiqs/qarrays/types.py
  dynamiqs/qarrays/utils.py
  dynamiqs/random.py
  dynamiqs/utils/jax_utils.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/states.py
Labels: bug, 🫴🏼 utils

#676 Sparse dia `__repr__` and fix associated doctest
  dynamiqs/qarrays/sparse_dia_qarray.py
  dynamiqs/time_array.py
  dynamiqs/utils/operators.py
Labels: feature, 🔧 technical

#677 Remove sparse hadamard implementation
  dynamiqs/utils/operators.py
Labels: bug, 🫴🏼 utils

#679 Simplify matrix layout selection
  dynamiqs/__init__.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/qarrays/utils.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/matrix_format_selector.py
  dynamiqs/utils/operators.py
  mkdocs.yml
  tests/utils/test_operators.py
  tests/utils/test_operators_dispatch.py
Labels: organisation, 🫴🏼 utils

#678 Adapt base integrator, saved and result classes to new solvers structure
  README.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/examples.md
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/mepropagator/expm_integrator.py
  dynamiqs/integrators/mesolve/expm_integrator.py
  dynamiqs/integrators/sepropagator/expm_integrator.py
  dynamiqs/integrators/sesolve/expm_integrator.py
  dynamiqs/options.py
  dynamiqs/result.py
  mkdocs.yml
Labels: organisation, 🌀 solvers
