Repository dynamiqs/dynamiqs, pull requests merged in 2024-12, with the labels that each got.

#814 Fix readme PyPI
  README_PYPI.md
Labels: bug, 📚 documentation

#813 Add `block_until_ready()` method to qarrays
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: bug, 🫴🏼 utils

#815 Update version `v0.2.2` -> `v0.2.3`
  dynamiqs/__init__.py
Labels: organisation, 🪛 tooling

#818 Move sparse DIA from coming soon to features
  README.md
  README_PYPI.md
  docs/documentation/getting_started/whatis.md
Labels: 📚 documentation, feature

#819 Document qarraylike objects
  docs/python_api/index.md
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/utils.py
  mkdocs.yml
Labels: 📚 documentation, feature

#817 Fix `ptrace` for qarrays
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/utils/quantum_utils/general.py
Labels: bug, 🫴🏼 utils

#820 Simplify documentation management and directory structure
  docs/generate_python_api.py
  docs/python_api/index.md
  docs/templates/python/material/table.html.jinja
  dynamiqs/dark/dark.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/integrators/mesolve/rouchon_integrator.py
  dynamiqs/plot/fock.py
  dynamiqs/random.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/general.py
  dynamiqs/utils/jax_utils.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/quantum_utils/__init__.py
  dynamiqs/utils/states.py
  dynamiqs/utils/vectorization.py
  dynamiqs/utils/wigner_utils.py
  mkdocs.yml
  tests/test_plot.py
Labels: bug, 📚 documentation

#821 Introduce layout attribute for timearrays
  dynamiqs/qarrays/layout.py
  dynamiqs/time_array.py
Labels: feature, 🔧 technical

#822 Fix tutorials in dev-qarray
  docs/documentation/advanced_examples/kerr-oscillator.md
  docs/documentation/basics/time-dependent-operators.md
  docs/documentation/basics/workflow.md
Labels: bug, 📚 documentation

#823 Add gradient conjuguate to sharp bits
  docs/documentation/getting_started/sharp-bits.md
Labels: 📚 documentation, feature

#828 Update dependencies
  pyproject.toml
Labels: feature, 🪛 tooling

#829 Add warning for matrix exponential
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: feature, 🫴🏼 utils

#830 Fix `Expm` solver to always use dense generators
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/solver.py
Labels: feature, 🌀 solvers

#831 Introduce a equinox runtime error check for sparsedia out-of-bounds elements
  dynamiqs/qarrays/sparsedia_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
Labels: feature, 🔧 technical

#826 Fix internal sums of QArrays
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/qarrays/utils.py
  dynamiqs/utils/vectorization.py
Labels: bug, 🔧 technical

#833 Temporary fix for sharp bits for documentation deployment
  docs/documentation/getting_started/sharp-bits.md
Labels: bug, 📚 documentation

#835 Fix propagator tests
  tests/mepropagator/test_batching.py
  tests/mepropagator/test_expm.py
  tests/sepropagator/test_sepropagator.py
Labels: bug, 🎯 tests

#834 Rehaul qarray warnings and checks
  dynamiqs/_utils.py
  dynamiqs/plot/wigner.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/utils/general.py
  tests/qarrays/test_dense_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
Labels: feature, 🔧 technical

#837 Add layout conversion methods to base class
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: 📚 documentation, 🫴🏼 utils

#838 Various small nits and renamings
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/utils/general.py
  dynamiqs/utils/vectorization.py
Labels: organisation, 🫴🏼 utils

#840 Fix incorrect dims check in dense qarray
  dynamiqs/qarrays/dense_qarray.py
Labels: bug, 🫴🏼 utils

#839 Fix sharp bits tutorial
  docs/documentation/getting_started/sharp-bits.md
  dynamiqs/qarrays/qarray.py
Labels: bug, 📚 documentation

#843 Uncomment floquet example
  dynamiqs/integrators/apis/floquet.py
Labels: bug, 📚 documentation

#844 Fix floquet product
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/floquet/floquet_integrator.py
Labels: bug, 🔧 technical

#842 Support vectorised qarrays
  docs/documentation/basics/open-systems.md
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/vectorization.py
  tests/qarrays/test_sparse_dia_qarray.py
Labels: feature, 🫴🏼 utils

#846 Update JAX dependency following diffrax 0.6.1 release
  pyproject.toml
Labels: bug, 🔧 technical

#848 Fix unneeded `np.asarray` in numpy_to_tuple helper function
  dynamiqs/qarrays/sparsedia_primitives.py
Labels: bug, 🔧 technical

#845 Fix a sparse to dense conversion warning during floquet tests
  dynamiqs/time_array.py
  tests/floquet/floquet_qubit.py
Labels: bug, 🎯 tests

#851 Remove `dev-qarray` from CI
  .github/workflows/ci.yml
  .github/workflows/publish-doc-dev-qarray.yml
Labels: organisation, 🎯 tests

#849 Fix the Wigner transpose bug
  dynamiqs/plot/wigner.py
  dynamiqs/utils/wigner_utils.py
Labels: bug, 🫴🏼 utils

#852 Add tests for wigner bug
  tests/utils/test_wigner.py
Labels: feature, 🎯 tests

#853 Renamed time arrays to time qarrays
  docs/documentation/basics/batching-simulations.md
  docs/documentation/basics/time-dependent-operators.md
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/time_qarray.py
  mkdocs.yml
  tests/floquet/floquet_qubit.py
  tests/mepropagator/test_expm.py
  tests/mesolve/open_system.py
  tests/sepropagator/test_sepropagator.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_batching.py
  tests/system.py
  tests/test_time_qarray.py
Labels: organisation, 🫴🏼 utils

#856 Fix skipped tests
  dynamiqs/time_qarray.py
  tests/sesolve/test_batching.py
  tests/test_time_qarray.py
Labels: bug, 🎯 tests

#860 Ignore Ruff SLF001 for calling private functions.
  dynamiqs/dark/dark.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/floquet/floquet_integrator.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/utils/general.py
  dynamiqs/utils/vectorization.py
  pyproject.toml
Labels: feature, 🪛 tooling

#859 Add test priority
  pyproject.toml
  tests/conftest.py
  tests/floquet/test_adaptive.py
  tests/floquet/test_batching.py
  tests/mepropagator/test_batching.py
  tests/mepropagator/test_expm.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_batching.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_expm.py
  tests/mesolve/test_rouchon.py
  tests/order.py
  tests/qarrays/test_dense_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
  tests/qarrays/test_utils.py
  tests/sepropagator/test_sepropagator.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_batching.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_expm.py
  tests/test_plot.py
  tests/test_time_qarray.py
  tests/utils/test_operators.py
  tests/utils/test_states.py
  tests/utils/test_utils.py
  tests/utils/test_wigner.py
Labels: feature, 🎯 tests

#862 Fix the Floquet periodicity check using `eqx.tree_at`
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: feature, 🌀 solvers

#863 Uniformize qarray and time-qarray documentation
  dynamiqs/qarrays/qarray.py
  dynamiqs/time_qarray.py
Labels: 📚 documentation, feature

#864 Fix the key check for SparseDIAQArray __getitem__
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: bug, 🔧 technical

#865 Dense conversion for eigen-decompositions of sparsedia qarrays
  dynamiqs/dark/dark.py
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: feature, 🔧 technical

#866 Introduce a class property `out_axes` for Results
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/result.py
Labels: feature, 🔧 technical

#868 Uniformize naming conventions
  docs/documentation/basics/batching-simulations.md
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/documentation/basics/time-dependent-operators.md
  docs/documentation/basics/workflow.md
  docs/glossary.md
  dynamiqs/_utils.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/result.py
  dynamiqs/time_qarray.py
  dynamiqs/utils/general.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/states.py
  dynamiqs/utils/vectorization.py
  dynamiqs/utils/wigner_utils.py
Labels: 📚 documentation, feature

#870 Various nits (missing test ordering, uniformise imports, deprecated class property, typing, doc)
  docs/conftest.py
  docs/documentation/advanced_examples/kerr-oscillator.md
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/documentation/basics/workflow.md
  dynamiqs/conftest.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/result.py
  tests/conftest.py
  tests/floquet/test_batching.py
  tests/mepropagator/test_batching.py
  tests/mesolve/test_batching.py
  tests/qarrays/test_dense_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
  tests/qarrays/test_utils.py
  tests/sesolve/test_batching.py
  tests/test_plot.py
  tests/test_time_qarray.py
  tests/utils/test_operators.py
  tests/utils/test_states.py
  tests/utils/test_utils.py
  tests/utils/test_wigner.py
Labels: bug, 🫴🏼 utils

#873 Always ensure a fixed memory usage
  dynamiqs/integrators/dsmesolve/fixed_step_integrator.py
Labels: bug, 🌀 solvers

#872 Add edge case for sparse @ sparse matmul
  dynamiqs/qarrays/sparsedia_primitives.py
Labels: bug, 🔧 technical

#874 Check `tsave` is linearly spaced with values multiple of `dt`
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/dsmesolve/fixed_step_integrator.py
Labels: feature, 🌀 solvers

#875 Merge main into dev-smesolve
  docs/conftest.py
  docs/documentation/advanced_examples/kerr-oscillator.md
  docs/documentation/advanced_examples/monitored-oscillator.md
  docs/documentation/advanced_examples/monitored-qubit.md
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/documentation/basics/workflow.md
  dynamiqs/conftest.py
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/qarrays/sparsedia_primitives.py
  dynamiqs/result.py
  tests/conftest.py
  tests/floquet/test_batching.py
  tests/mepropagator/test_batching.py
  tests/mesolve/test_batching.py
  tests/qarrays/test_dense_qarray.py
  tests/qarrays/test_sparse_dia_qarray.py
  tests/qarrays/test_utils.py
  tests/sesolve/test_batching.py
  tests/test_plot.py
  tests/test_time_qarray.py
  tests/utils/test_operators.py
  tests/utils/test_states.py
  tests/utils/test_utils.py
  tests/utils/test_wigner.py
Labels: organisation, 🔧 technical

#871 Fix elmul implementation
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: bug, 🔧 technical

#876 Handle edge cases gracefully (`self.options.t0`, time-qarray `discontinuity_ts`)
  dynamiqs/integrators/dsmesolve/fixed_step_integrator.py
Labels: feature, 🌀 solvers

#878 Minor nits on smesolve (remove noqa, remove CI and remove publish doc website)
  .github/workflows/ci.yml
  .github/workflows/publish-doc-dev-smesolve.yml
  dynamiqs/integrators/apis/dsmesolve.py
Labels: organisation, 🪛 tooling

#880 Fix dsmesolve cartesian batching
  dynamiqs/integrators/apis/dsmesolve.py
Labels: bug, 🌀 solvers

#879 Replace `logging.warning` by `warnings.warn`
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
Labels: organisation, 🔧 technical

#883 Nits qarray merge documentation
  CONTRIBUTING.md
  docs/community/contributing.md
  docs/documentation/basics/batching-simulations.md
  docs/documentation/basics/workflow.md
  docs/glossary.md
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/solver.py
  dynamiqs/utils/general.py
  tests/sepropagator/test_sepropagator.py
  tests/sesolve/test_batching.py
  tests/utils/test_states.py
Labels: bug, 📚 documentation

#884 Various small bug fixes (`cd_gate` definition, mixed layout `exp_ops`, typing and examples)
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/utils/general.py
  dynamiqs/utils/optimal_control.py
Labels: bug, 🔧 technical

#885 Add `dq.eye_like()` and `dq.zero_like()` operators
  docs/python_api/index.md
  dynamiqs/utils/operators.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#882 Remove abstraction hell
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/floquet_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/rouchon_integrator.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/integrators/floquet/__init__.py
  dynamiqs/integrators/mepropagator/__init__.py
  dynamiqs/integrators/mepropagator/expm_integrator.py
  dynamiqs/integrators/mesolve/__init__.py
  dynamiqs/integrators/mesolve/diffrax_integrator.py
  dynamiqs/integrators/mesolve/expm_integrator.py
  dynamiqs/integrators/sepropagator/__init__.py
  dynamiqs/integrators/sepropagator/diffrax_integrator.py
  dynamiqs/integrators/sepropagator/expm_integrator.py
  dynamiqs/integrators/sesolve/__init__.py
  dynamiqs/integrators/sesolve/diffrax_integrator.py
  dynamiqs/integrators/sesolve/expm_integrator.py
  dynamiqs/integrators/smesolve/__init__.py
Labels: organisation, 🔧 technical
