Repository dynamiqs/dynamiqs, pull requests merged in 2024-02, with the labels that each got.

#423 Fix tasks
  benchmarks/systems/cat_cnot.py
  docs/python_api/index.md
  dynamiqs/mesolve/lindblad_term.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/options.py
  dynamiqs/plots/namespace.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_wigner.py
  dynamiqs/rand.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/wigners.py
  mkdocs.yml
  pyproject.toml
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/smesolve/sme_solver_tester.py
  tests/smesolve/test_euler.py
  tests/smesolve/test_rouchon.py
  tests/solver_tester.py
  tests/test_plots.py
  tests/test_time_array.py
  tests/utils/test_utils.py
Labels: 🪛 tooling

#424 Simpler ptrace JIT
  dynamiqs/rand.py
  dynamiqs/utils/utils.py
Labels: 🔧 technical, 🫴🏼 utils

#425 Advertise transition to JAX on README
  README.md
  docs/getting_started/whatis.md
  pyproject.toml
Labels: 📚 documentation

#429 JIT `sesolve`
  dynamiqs/__init__.py
  dynamiqs/_utils.py
  dynamiqs/gradient.py
  dynamiqs/options.py
  dynamiqs/result.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solver.py
Labels: 🌀 solvers, 🔧 technical

#430 Fix sesolve tests
  dynamiqs/sesolve/sesolve.py
  dynamiqs/time_array.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_backward_euler.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/solver_tester.py
  tests/system.py
  tests_old/mesolve/__init__.py
  tests_old/mesolve/open_system.py
  tests_old/mesolve/test_adaptive.py
  tests_old/mesolve/test_euler.py
  tests_old/mesolve/test_propagator.py
  tests_old/mesolve/test_rouchon.py
  tests_old/smesolve/__init__.py
  tests_old/smesolve/monitored_system.py
  tests_old/smesolve/sme_solver_tester.py
  tests_old/smesolve/test_euler.py
  tests_old/smesolve/test_rouchon.py
Labels: 🎯 tests

#431 Implement base solver
  dynamiqs/_utils.py
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/result.py
  dynamiqs/sesolve/sediffrax.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solver.py
Labels: organisation, 🌀 solvers

#432 Minor fixes to the test
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_backward_euler.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
  tests/system.py
Labels: 🎯 tests

#433 JIT mesolve
  dynamiqs/__init__.py
  dynamiqs/mesolve/lindblad_term.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/mesolve/mesolve.py
  mesolve_old/rouchon.py
  tests/mesolve/__init__.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests_old/mesolve/open_system.py
  tests_old/mesolve/test_adaptive.py
  tests_old/mesolve/test_euler.py
Labels: 🌀 solvers, 🔧 technical

#434 Simplify sesolve mesolve
  dynamiqs/core/_utils.py
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  tests/mesolve/open_system.py
  tests/mesolve/test_dopri5.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_dopri5.py
  tests/system.py
Labels: organisation, 🌀 solvers

#435 Fix doctest figures
  docs/conftest.py
  dynamiqs/conftest.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_wigner.py
  dynamiqs/smesolve/__init__.py
  dynamiqs/smesolve/smesolve.py
  tests/conftest.py
  tests/test_plots.py
Labels: 📚 documentation, 🔧 technical

#436 Batch sesolve
  dynamiqs/__init__.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/rand.py
  dynamiqs/sesolve/sesolve.py
  pyproject.toml
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_batching.py
  tests/solver_tester.py
  tests/system.py
Labels: feature, 🌀 solvers

#438 Add CI on jax branch
  .github/workflows/ci.yml
Labels: 🪛 tooling

#443 Remove `dtype` argument
  dynamiqs/core/_utils.py
  dynamiqs/dark/dark.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/options.py
  dynamiqs/rand.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/time_array.py
  dynamiqs/utils/array_types.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/states.py
  dynamiqs/utils/wigners.py
  tests/utils/test_utils.py
Labels: 🔧 technical, 🫴🏼 utils

#445 Faster dm fidelity which is compatible with GPU
  dynamiqs/utils/utils.py
Labels: bug, 🫴🏼 utils

#444 Update tests readme with tdqubit formulas
  .pre-commit-config.yaml
  tests/README.md
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
Labels: 📚 documentation, 🎯 tests

#448 Batch expect
  dynamiqs/_utils.py
  dynamiqs/core/abstract_solver.py
  dynamiqs/utils/utils.py
Labels: feature, 🫴🏼 utils

#449 Add initial time `t0` option
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/core/propagator_solver.py
  dynamiqs/options.py
Labels: feature, 🌀 solvers

#451 Fallback method for `dm_fidelity` on GPU
  dynamiqs/_utils.py
  dynamiqs/utils/utils.py
Labels: bug, 🫴🏼 utils

#454 Remove old code that was copy-pasted in separated directory
  dynamiqs_old/gradient.py
  dynamiqs_old/mesolve/__init__.py
  dynamiqs_old/mesolve/adaptive.py
  dynamiqs_old/mesolve/euler.py
  dynamiqs_old/mesolve/me_solver.py
  dynamiqs_old/mesolve/mesolve.py
  dynamiqs_old/mesolve/propagator.py
  dynamiqs_old/mesolve/rouchon.py
  dynamiqs_old/sesolve/__init__.py
  dynamiqs_old/sesolve/adaptive.py
  dynamiqs_old/sesolve/backward_euler.py
  dynamiqs_old/sesolve/euler.py
  dynamiqs_old/sesolve/propagator.py
  dynamiqs_old/sesolve/sesolve.py
  dynamiqs_old/smesolve/__init__.py
  dynamiqs_old/smesolve/euler.py
  dynamiqs_old/smesolve/rouchon.py
  dynamiqs_old/smesolve/sme_solver.py
  dynamiqs_old/smesolve/smesolve.py
  dynamiqs_old/solver.py
  dynamiqs_old/solvers/__init__.py
  dynamiqs_old/solvers/ode/__init__.py
  dynamiqs_old/solvers/ode/adaptive_solver.py
  dynamiqs_old/solvers/ode/adjoint_ode_solver.py
  dynamiqs_old/solvers/ode/fixed_solver.py
  dynamiqs_old/solvers/ode/ode_solver.py
  dynamiqs_old/solvers/options.py
  dynamiqs_old/solvers/propagator.py
  dynamiqs_old/solvers/result.py
  dynamiqs_old/solvers/solver.py
  dynamiqs_old/solvers/utils/__init__.py
  dynamiqs_old/solvers/utils/utils.py
  mesolve_old/rouchon.py
Labels: organisation

#453 Save last state if `save_states=False`
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/core/propagator_solver.py
Labels: feature, 🌀 solvers

#452 New ODE solvers: Dopri8 and Tsit5
  dynamiqs/core/diffrax_solver.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sediffrax.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solver.py
  tests/mesolve/test_adaptive.py
  tests/sesolve/test_adaptive.py
  tests/solver_tester.py
Labels: feature, 🌀 solvers

#458 Fix minor bugs
  dynamiqs/core/propagator_solver.py
  dynamiqs/solver.py
Labels: bug

#456 Remove dq.rand namespace
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/rand.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/random.py
  mkdocs.yml
  tests/mesolve/test_batching.py
  tests/sesolve/test_batching.py
  tests/utils/test_utils.py
Labels: feature

#460 Replace adjoint by checkpointed autograd
  dynamiqs/core/diffrax_solver.py
  dynamiqs/gradient.py
  dynamiqs/solver.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_propagator.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_propagator.py
Labels: organisation, 🌀 solvers

#462 Update default solver tolerence
  dynamiqs/solver.py
Labels: 🌀 solvers

#461 Start moving documentation to JAX
  README.md
  docs/getting_started/examples.md
  docs/getting_started/sharp-bits.md
  docs/getting_started/whatis.md
  docs/overrides/home.html
  docs/tutorials/batching-simulations.md
  docs/tutorials/closed-system.md
  docs/tutorials/defining-hamiltonians.md
  docs/tutorials/open-system.md
  docs/tutorials/workflow.md
  pyproject.toml
Labels: 📚 documentation

#464 Add documentation for missing API
  README.md
  docs/generate_python_api.py
  docs/getting_started/whatis.md
  docs/python_api/index.md
  docs/python_api/options/Options.md
  docs/python_api/result/Result.md
  docs/python_api/solvers/mesolve.md
  docs/python_api/solvers/sesolve.md
  docs/python_api/solvers/smesolve.md
  docs/python_api/totime/totime.md
  docs/templates/python/material/class.html
  docs/templates/python/material/docstring/attributes.html
  docs/templates/python/material/function.html
  docs/templates/python/material/table.html
  docs/tutorials/batching-simulations.md
  docs/tutorials/defining-hamiltonians.md
  dynamiqs/gradient.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/options.py
  dynamiqs/result.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solver.py
  dynamiqs/time_array.py
  mkdocs.yml
Labels: 📚 documentation

#471 Add ruff
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  benchmarks/systems/cat_cnot.py
  benchmarks/systems/system.py
  benchmarks/systems/transmon_gate.py
  docs/conftest.py
  docs/generate_python_api.py
  docs/getting_started/contributing.md
  dynamiqs/__init__.py
  dynamiqs/_utils.py
  dynamiqs/conftest.py
  dynamiqs/core/__init__.py
  dynamiqs/core/_utils.py
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/core/propagator_solver.py
  dynamiqs/gradient.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/mesolve/mepropagator.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_hinton.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/plots/utils.py
  dynamiqs/result.py
  dynamiqs/sesolve/sediffrax.py
  dynamiqs/sesolve/sepropagator.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solver.py
  dynamiqs/time_array.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/random.py
  dynamiqs/utils/states.py
  dynamiqs/utils/utils.py
  dynamiqs/utils/vectorization.py
  dynamiqs/utils/wigners.py
  pyproject.toml
  setup.cfg
  tests/conftest.py
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
  tests/solver_tester.py
  tests/system.py
  tests/test_plots.py
  tests/test_time_array.py
  tests/utils/test_utils.py
Labels: feature, 🪛 tooling

#473 Update library version to 0.2.0
  pyproject.toml
Labels: organisation

#474 Fix remaining warning about jax
  docs/getting_started/whatis.md
Labels: bug, 📚 documentation

#475 Add solver infos
  README.md
  docs/getting_started/examples.md
  docs/tutorials/batching-simulations.md
  docs/tutorials/workflow.md
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/core/propagator_solver.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/result.py
  dynamiqs/sesolve/sesolve.py
Labels: feature, 🌀 solvers

#468 Add support for arbitrary jump_ops batching
  dynamiqs/core/_utils.py
  dynamiqs/mesolve/mesolve.py
  tests/mesolve/test_batching.py
Labels: bug

#478 Remove incomplete documentation on `jump_ops` batching
  dynamiqs/mesolve/mesolve.py
  dynamiqs/smesolve/smesolve.py
Labels: 📚 documentation

#479 Add black to dependencies to fix function signatures in doc
  pyproject.toml
Labels: bug, 📚 documentation

#480 Document and improve plot_wigner_gif
  dynamiqs/plots/plots_wigner.py
Labels: feature, 🎨 plot

#476 Refactor TimeArrays to properly deal with `jax.vmap`
  docs/tutorials/defining-hamiltonians.md
  dynamiqs/time_array.py
  pyproject.toml
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
  tests/test_time_array.py
Labels: bug

#477 Implement sums of TimeArrays
  dynamiqs/time_array.py
  tests/test_time_array.py
Labels: feature

#483 Speedup `Tr[A @ B]` by computing `(A * B).sum()`
  docs/python_api/index.md
  dynamiqs/utils/utils.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils
