Repository dynamiqs/dynamiqs, pull requests merged in 2024-06, with the labels that each got.

#599 Update tqdm bar format
  dynamiqs/progress_meter.py
Labels: feature, 🔧 technical

#597 Add `Rouchon1` solver
  dynamiqs/core/diffrax_solver.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/mesolve/merouchon.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/solver.py
  tests/mesolve/test_rouchon.py
Labels: feature, 🌀 solvers

#595 Add implicit solvers to dynamiqs
  docs/python_api/index.md
  dynamiqs/core/diffrax_solver.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sediffrax.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solver.py
  mkdocs.yml
Labels: feature, 🌀 solvers

#594 Small doc improvements (annotations, implicite time in ODEs/SDEs)
  docs/documentation/basics/batching-simulations.md
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/stylesheets/extra.css
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  mkdocs.yml
Labels: 📚 documentation, feature

#601 Minor fixes to implicit solvers documentation
  README.md
  docs/documentation/getting_started/whatis.md
  dynamiqs/solver.py
Labels: bug, 📚 documentation

#600 Specify time-arrays discontinuities in diffrax solvers
  docs/documentation/basics/time-dependent-operators.md
  dynamiqs/_utils.py
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/time_array.py
Labels: bug, 🌀 solvers

#602 Add support for scalar in ModulatedTimeArray
  docs/documentation/basics/time-dependent-operators.md
  dynamiqs/time_array.py
Labels: bug, 🔧 technical

#567 Introduce QArrays
  dynamiqs/__init__.py
  dynamiqs/qarray.py
  dynamiqs/utils/utils/general.py
  tests/qarray.py
Labels: feature, 🫴🏼 utils

#577 Base structure for SparseQArray class
  dynamiqs/sparse_qarray.py
Labels: performance, 🔧 technical

#606 Remove `toop()`
  dynamiqs/utils/utils/general.py
Labels: organisation, 🫴🏼 utils

#611 Rename `QObj` to `Qobj`
  docs/documentation/getting_started/sharp-bits.md
Labels: bug, 📚 documentation

#615 Fix result none attributes from cartesian vectorization bug
  dynamiqs/core/_utils.py
  tests/mesolve/test_batching.py
Labels: bug, 🌀 solvers

#607 Move qarrays implementation to separate folder and split files
  dynamiqs/__init__.py
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_qarray.py
Labels: organisation, 🫴🏼 utils

#610 Small timearray improvements (renaming and readability)
  dynamiqs/time_array.py
Labels: organisation, 🫴🏼 utils

#608 Clean `QArray`
  dynamiqs/qarrays/qarray.py
Labels: organisation, 🫴🏼 utils

#609 Clean `DenseQArray`
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  tests/qarrays/__init__.py
  tests/qarrays/test_dense_qarray.py
Labels: organisation, 🫴🏼 utils

#612 Fix infos precision for batched simulation
  dynamiqs/core/diffrax_solver.py
  dynamiqs/core/propagator_solver.py
Labels: bug, 🌀 solvers

#613 Exclude JIT time from batching tutorial benchmarking
  docs/documentation/basics/batching-simulations.md
Labels: 📚 documentation, feature

#614 New progress meter format that suits any duration
  dynamiqs/progress_meter.py
Labels: feature, 🌀 solvers

#603 Add examples to timearray creation utilities
  dynamiqs/time_array.py
Labels: 📚 documentation, feature

#617 Update qutip minimal version from 4.0 to 4.7.5
  pyproject.toml
Labels: bug, 🔧 technical

#618 Add progress meter output to documentation and replace `np.*` by `jnp.*`
  README.md
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/examples.md
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_hinton.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/plots/plots_wigner.py
  dynamiqs/plots/utils.py
  dynamiqs/utils/random.py
Labels: 📚 documentation, feature

#619 Revert "Integrating SparseQArray in the dynamiqs workflow. (#591)"
  dynamiqs/__init__.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/qarrays/sparse_qarray.py
  dynamiqs/time_array.py
  tests/mesolve/open_system.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
Labels: organisation, 🔧 technical

#616 Merge and clean up SparseQArray with the rest of QArray
  dynamiqs/qarrays/__init__.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparse_qarray.py
  tests/qarrays/test_sparse_qarray.py
Labels: feature, 🔧 technical
