Repository dynamiqs/dynamiqs, pull requests merged in 2024-03, with the labels that each got.

#485 Fix Wigner computation indices offset
  dynamiqs/utils/wigners.py
Labels: bug, 🫴🏼 utils

#489 Update the API of TimeArray
  docs/generate_python_api.py
  docs/python_api/index.md
  docs/python_api/totime/totime.md
  docs/tutorials/defining-hamiltonians.md
  dynamiqs/__init__.py
  dynamiqs/_utils.py
  dynamiqs/core/_utils.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/time_array.py
  mkdocs.yml
  tests/mesolve/open_system.py
  tests/sesolve/closed_system.py
Labels: bug

#491 Minor fixes (remove `TimeArrayLike`, turn on docstring formatting)
  dynamiqs/time_array.py
  pyproject.toml
Labels: organisation

#493 Remove benchmarks directory (for now)
  benchmarks/__init__.py
  benchmarks/systems/README.md
  benchmarks/systems/__init__.py
  benchmarks/systems/cat_cnot.py
  benchmarks/systems/system.py
  benchmarks/systems/transmon_gate.py
Labels: organisation

#490 Add `dq.set_device()` and `dq.set_precision()` utilities
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/_utils.py
  dynamiqs/gradient.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/time_array.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/jax_utils.py
  dynamiqs/utils/operators.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/states.py
  dynamiqs/utils/wigners.py
  mkdocs.yml
  tests/utils/test_utils.py
Labels: feature, 🫴🏼 utils

#494 Improve documentation on defining Hamiltonians
  docs/tutorials/defining-hamiltonians.md
Labels: 📚 documentation

#492 Update README with new features, project philosophy and cite us section
  README.md
  docs/getting_started/cite-us.md
  docs/getting_started/contributing.md
  docs/getting_started/index.md
  docs/getting_started/more-features.md
  docs/getting_started/the-dynamiqs-project.md
  docs/getting_started/whatis.md
  mkdocs.yml
Labels: 📚 documentation, feature

#495 Add `dq.proj()`
  docs/python_api/index.md
  dynamiqs/utils/utils.py
  mkdocs.yml
  tests/test_plots.py
Labels: feature, 🫴🏼 utils

#496 Put time arrays first in documentation
  docs/python_api/index.md
  mkdocs.yml
Labels: 📚 documentation

#497 Fix result documentation
  docs/stylesheets/extra.css
  docs/templates/python/material/docstring/attributes.html
  docs/templates/python/material/table.html
Labels: 📚 documentation

#499 Rename Cite us to Citing dynamiqs
  README.md
  docs/getting_started/citing.md
  docs/getting_started/index.md
  mkdocs.yml
Labels: 📚 documentation

#500 Regroup sections inside Getting Started
  docs/getting_started/contributing.md
  docs/getting_started/index.md
  docs/getting_started/more-features.md
  docs/getting_started/talk.md
  docs/getting_started/the-dynamiqs-project.md
  docs/getting_started/whatis.md
  mkdocs.yml
Labels: 📚 documentation

#501 Add back documentation for lists and Qobjs
  docs/getting_started/sharp-bits.md
  docs/tutorials/batching-simulations.md
  docs/tutorials/closed-system.md
  docs/tutorials/defining-hamiltonians.md
  docs/tutorials/open-system.md
  docs/tutorials/workflow.md
Labels: 📚 documentation

#502 Minor fixes (documentation, type hints, useless code)
  docs/getting_started/sharp-bits.md
  dynamiqs/gradient.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/options.py
  dynamiqs/sesolve/sediffrax.py
Labels: organisation

#505 Fix doc API organisation
  docs/generate_python_api.py
  docs/getting_started/sharp-bits.md
  docs/python_api/index.md
  docs/python_api/options/Options.md
  docs/python_api/result/Result.md
  docs/python_api/solvers/mesolve.md
  docs/python_api/solvers/sesolve.md
  docs/python_api/solvers/smesolve.md
  docs/tutorials/batching-simulations.md
  docs/tutorials/closed-system.md
  docs/tutorials/defining-hamiltonians.md
  docs/tutorials/open-system.md
  docs/tutorials/workflow.md
  dynamiqs/__init__.py
  dynamiqs/mesolve/__init__.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/plots/__init__.py
  dynamiqs/plots/colormaps.py
  dynamiqs/plots/namespace.py
  dynamiqs/plots/plots_wigner.py
  dynamiqs/plots/utils.py
  dynamiqs/sesolve/__init__.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/__init__.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solvers.py
  dynamiqs/utils/__init__.py
  dynamiqs/utils/jax_utils.py
  dynamiqs/utils/utils/__init__.py
  dynamiqs/utils/utils/general.py
  dynamiqs/utils/utils/wigner.py
  dynamiqs/utils/vectorization.py
  mkdocs.yml
  pyproject.toml
  tests/test_plots.py
Labels: 📚 documentation

#504 Add slack logo to site header
  docs/overrides/partials/header.html
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: 📚 documentation

#506 Fix slack logo
  docs/overrides/partials/header.html
  mkdocs.yml
Labels: bug, 📚 documentation

#507 Move back contact infos as main section
  docs/getting_started/contributing.md
  docs/getting_started/index.md
  docs/getting_started/lets-talk.md
  mkdocs.yml
Labels: 📚 documentation

#508 Fix vector_field for Lindbladian calculation
  dynamiqs/mesolve/mediffrax.py
Labels: performance

#503 Document time arrays
  docs/getting_started/sharp-bits.md
  docs/python_api/index.md
  docs/stylesheets/extra.css
  docs/templates/python/material/attribute.html
  docs/templates/python/material/docstring/functions.html
  docs/templates/python/material/function.html
  docs/templates/python/material/labels.html
  docs/tutorials/defining-hamiltonians.md
  docs/tutorials/time-dependent-operators.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/time_array.py
  mkdocs.yml
Labels: 📚 documentation

#510 Add glossary and tooltips
  docs/tutorials/closed-system.md
  docs/tutorials/open-system.md
  docs/tutorials/time-dependent-operators.md
  docs/tutorials/workflow.md
  includes/glossary.md
  mkdocs.yml
Labels: 📚 documentation

#488 Add `dq.eingenstates()` and `dq.isherm()`
  dynamiqs/utils/utils/__init__.py
  dynamiqs/utils/utils/general.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#515 Minor fixes to `dq.is_herm()` documentation
  dynamiqs/utils/utils/general.py
Labels: 📚 documentation

#517 Fix comment on Lindblad equation stability
  dynamiqs/mesolve/mediffrax.py
Labels: 📚 documentation

#512 Minor technical fixes
  .gitignore
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/core/propagator_solver.py
  dynamiqs/gradient.py
  dynamiqs/mesolve/mediffrax.py
  dynamiqs/options.py
  dynamiqs/result.py
  dynamiqs/sesolve/sediffrax.py
  dynamiqs/solver.py
  dynamiqs/time_array.py
Labels: 🔧 technical

#513 Decouple results for sesolve/mesolve
  README.md
  docs/getting_started/examples.md
  docs/python_api/index.md
  docs/tutorials/batching-simulations.md
  docs/tutorials/workflow.md
  dynamiqs/core/abstract_solver.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/core/propagator_solver.py
  dynamiqs/mesolve/mepropagator.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/result.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  mkdocs.yml
  tests/mesolve/test_batching.py
  tests/sesolve/test_batching.py
Labels: 🔧 technical

#514 Document supported solvers and gradients
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/solver.py
Labels: 📚 documentation

#522 Implements cos and sin for matrices
  docs/getting_started/sharp-bits.md
  docs/tutorials/time-dependent-operators.md
  dynamiqs/utils/utils/__init__.py
  dynamiqs/utils/utils/general.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#523 Remove matplotlib DeprecationWarning
  dynamiqs/plots/plots_hinton.py
  dynamiqs/plots/utils.py
  pyproject.toml
Labels: bug

#520 Fix imageio "fps" deprecation warning.
  dynamiqs/plots/plots_wigner.py
Labels: bug

#525 Fix imageio duration argument for wigner gif
  dynamiqs/plots/plots_wigner.py
Labels: bug, 🎨 plot

#524 Fix bug with save_states=False
  dynamiqs/core/abstract_solver.py
Labels: bug, 🌀 solvers

#526 Fix imageio duration argument for wigner gif (re-fix)
  dynamiqs/plots/plots_wigner.py
Labels: bug, 🎨 plot

#527 Verify the shape of `ArrayLike` arguments in public API
  dynamiqs/_checks.py
  dynamiqs/_utils.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_hinton.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/plots/plots_wigner.py
  dynamiqs/time_array.py
  dynamiqs/utils/jax_utils.py
  dynamiqs/utils/optimal_control.py
  dynamiqs/utils/random.py
  dynamiqs/utils/utils/general.py
  dynamiqs/utils/utils/wigner.py
  dynamiqs/utils/vectorization.py
Labels: feature, 🫴🏼 utils

#521 Check args dimensions for mesolve/sesolve
  dynamiqs/_checks.py
  dynamiqs/core/_utils.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
Labels: feature, 🌀 solvers

#531 Set QuTiP version to 4 for now
  pyproject.toml
Labels: organisation

#530 Fix `dq.spost()` formula to use transpose instead of adjoint
  dynamiqs/utils/vectorization.py
Labels: bug, 🫴🏼 utils

#532 Fix JIT sesolve/mesolve broken by runtime check
  dynamiqs/_checks.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/time_array.py
Labels: bug, 🌀 solvers

#511 Add `__str__` for solvers and gradients
  dynamiqs/_utils.py
  dynamiqs/gradient.py
  dynamiqs/options.py
  dynamiqs/solver.py
Labels: feature, 🫴🏼 utils
