Repository dynamiqs/dynamiqs, pull requests merged in 2024-05, with the labels that each got.

#559 Faster `sqrtm()` by leveraging broadcasting
  dynamiqs/utils/utils/general.py
Labels: performance, 🫴🏼 utils

#560 Improve `dq.tracemm` documentation
  docs/javascripts/katex.js
  dynamiqs/utils/utils/__init__.py
  dynamiqs/utils/utils/general.py
  mkdocs.yml
Labels: 📚 documentation, 🫴🏼 utils

#565 Various minor fixes of the new time-array backend
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/time_array.py
Labels: organisation, 🔧 technical

#564 Reorganize cartesian and flat batching tests
  tests/mesolve/test_batching.py
  tests/sesolve/test_batching.py
Labels: organisation, 🎯 tests

#562 Add new batching API for time arrays and support for ND batching
  docs/tutorials/time-dependent-operators.md
  dynamiqs/core/_utils.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/options.py
  dynamiqs/result.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/time_array.py
  tests/mesolve/open_system.py
  tests/mesolve/test_batching.py
  tests/sesolve/closed_system.py
  tests/sesolve/test_batching.py
  tests/solver_tester.py
  tests/test_time_array.py
Labels: feature, 🔧 technical

#563 Catch `XLARuntimeError` to raise a more friendly exception
  dynamiqs/core/_utils.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/sesolve/sesolve.py
Labels: feature, 🌀 solvers

#569 Add `dq.expm()`
  dynamiqs/utils/utils/__init__.py
  dynamiqs/utils/utils/general.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#566 Small improvements to time array tutorial
  docs/tutorials/time-dependent-operators.md
  dynamiqs/time_array.py
Labels: 📚 documentation, 🫴🏼 utils

#570 Rework tutorials index
  docs/tutorials/closed-systems.md
  docs/tutorials/index.md
  docs/tutorials/open-systems.md
  mkdocs.yml
Labels: 📚 documentation, organisation

#571 Minor improvements to workflow tutorial
  docs/tutorials/workflow.md
Labels: 📚 documentation, feature

#572 Improve documentation styling
  docs/stylesheets/extra.css
  docs/stylesheets/theme.css
  docs/templates/python/material/docstring/admonition.html
  docs/tutorials/time-dependent-operators.md
  dynamiqs/gradient.py
  dynamiqs/mesolve/mesolve.py
  dynamiqs/plots/utils.py
  dynamiqs/result.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  dynamiqs/solver.py
  dynamiqs/time_array.py
  dynamiqs/utils/jax_utils.py
  dynamiqs/utils/random.py
  dynamiqs/utils/utils/general.py
  dynamiqs/utils/vectorization.py
  mkdocs.yml
Labels: 📚 documentation, feature

#574 Rename figs-code to figs_code and figs-docs to figs_docs
  .gitignore
  docs/conftest.py
  docs/figs_code/.gitkeep
  docs/figs_docs/.gitkeep
  docs/tutorials/workflow.md
  dynamiqs/conftest.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/plots_hinton.py
  dynamiqs/plots/plots_misc.py
  dynamiqs/plots/plots_wigner.py
  dynamiqs/plots/utils.py
  dynamiqs/utils/random.py
  pyproject.toml
Labels: 📚 documentation, feature

#575 Reorganize documentation sections
  docs/community/citing.md
  docs/community/contributing.md
  docs/community/index.md
  docs/community/lets-talk.md
  docs/documentation/basics/batching-simulations.md
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/computing-gradients.md
  docs/documentation/basics/open-systems.md
  docs/documentation/basics/time-dependent-operators.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/examples.md
  docs/documentation/getting_started/installation.md
  docs/documentation/getting_started/sharp-bits.md
  docs/documentation/getting_started/whatis.md
  docs/documentation/index.md
  docs/getting_started/index.md
  docs/tutorials/index.md
  dynamiqs/mesolve/mesolve.py
  dynamiqs/result.py
  dynamiqs/sesolve/sesolve.py
  dynamiqs/smesolve/smesolve.py
  mkdocs.yml
Labels: 📚 documentation, feature

#576 Minor rephrasings in the documentation
  README.md
  docs/community/index.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/whatis.md
  docs/documentation/index.md
Labels: 📚 documentation, feature

#579 Update navigation styling in docs
  docs/stylesheets/extra.css
Labels: 📚 documentation, feature

#580 Various small fixes (fock plots, default matmul precision, directory structure)
  docs/glossary.md
  dynamiqs/__init__.py
  dynamiqs/plots/plots_fock.py
  dynamiqs/plots/utils.py
  mkdocs.yml
  pyproject.toml
Labels: bug, 📚 documentation

#584 Add documentation titled code blocks, content tabs and icons
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  docs/documentation/basics/time-dependent-operators.md
  docs/documentation/basics/workflow.md
  docs/documentation/getting_started/examples.md
  docs/documentation/getting_started/sharp-bits.md
  dynamiqs/plots/plots_hinton.py
  dynamiqs/result.py
  mkdocs.yml
Labels: 📚 documentation, feature

#428 Add progress bar
  dynamiqs/__init__.py
  dynamiqs/core/diffrax_solver.py
  dynamiqs/options.py
  dynamiqs/progress_meter.py
Labels: feature, 🌀 solvers

#589 New progress bar format
  dynamiqs/progress_meter.py
  pyproject.toml
Labels: feature, 🌀 solvers

#582 Generalize dq.fock and dq.coherent to allow for batching and multi-mode initialization
  dynamiqs/_checks.py
  dynamiqs/utils/states.py
Labels: feature, 🫴🏼 utils

#578 Update the batching tutorial with the new API
  docs/documentation/basics/batching-simulations.md
  dynamiqs/time_array.py
Labels: 📚 documentation, feature

#593 Add `dq.ground()` and `dq.excited()`
  docs/documentation/basics/closed-systems.md
  docs/documentation/basics/open-systems.md
  dynamiqs/utils/states.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#598 Explain where extra saved data can be retrieved in options documentation
  dynamiqs/options.py
  dynamiqs/result.py
Labels: 📚 documentation, feature
