Repository dynamiqs/dynamiqs, pull requests merged in 2025-04, with the labels that each got.

#943 Implement `smart_sampling` for `dq.jssesolve()`
  dynamiqs/integrators/apis/jssesolve.py
  dynamiqs/integrators/core/event_integrator.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/result.py
  tests/jssesolve/test_jssesolve.py
Labels: feature, 🌀 solvers

#955 Fix bug that didn't allow for scalar outputs of modulated functions
  dynamiqs/time_qarray.py
Labels: bug, 🔧 technical

#951 Make `method` a non-static argument for all solvers
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/dssesolve.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/jssesolve.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/method.py
  dynamiqs/result.py
Labels: feature, 🌀 solvers

#959 Fix documentation index.md
  docs/documentation/index.md
Labels: bug, 📚 documentation
