Repository dynamiqs/dynamiqs, pull requests merged in 2025-03, with the labels that each got.

#923 Fix printing patterns for SparseDIAQArray in scientific format
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: bug, 🔧 technical

#924 Fix matrix multiplication of dense @ sparse
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/sparsedia_primitives.py
Labels: bug, 🔧 technical

#925 Remove normalization warning in `dq.wigner()` (not jit-compatible)
  dynamiqs/_checks.py
  dynamiqs/utils/wigner_utils.py
Labels: bug, 🔧 technical

#927 Fix public/private methods convention
  docs/conftest.py
  dynamiqs/_utils.py
  dynamiqs/conftest.py
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
  dynamiqs/integrators/core/rouchon_integrator.py
  dynamiqs/plot/wigner.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  tests/conftest.py
Labels: organisation, 🫴🏼 utils

#928 Add qarray matmul priority mechanism
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: organisation, 🫴🏼 utils

#929 Add qarray `x.mean()` method
  dynamiqs/qarrays/qarray.py
Labels: feature, 🫴🏼 utils

#748 Add an `Event` solver for `dq.jssesolve()`
  docs/python_api/index.md
  dynamiqs/integrators/apis/dssesolve.py
  dynamiqs/integrators/apis/jsmesolve.py
  dynamiqs/integrators/apis/jssesolve.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/event_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/method.py
  dynamiqs/options.py
  dynamiqs/result.py
  mkdocs.yml
  pyproject.toml
  tests/jssesolve/__init__.py
  tests/jssesolve/test_batching.py
  tests/jssesolve/test_jssesolve.py
Labels: feature, 🌀 solvers

#930 Fix paper citation date and authors order
  README.md
  README_PYPI.md
  docs/community/citing.md
Labels: organisation, 🪛 tooling

#931 Add global setting to set a default progress meter
  docs/documentation/advanced_examples/kerr-oscillator.md
  docs/documentation/basics/batching-simulations.md
  docs/python_api/index.md
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/dssesolve.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/jssesolve.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/options.py
  dynamiqs/utils/global_settings.py
  mkdocs.yml
Labels: feature, 🌀 solvers

#933 Use `_replace()` to simplify timeqarray implementation
  dynamiqs/time_qarray.py
Labels: organisation, 🔧 technical

#934 Simplify `__add__` in timeqarray
  dynamiqs/time_qarray.py
Labels: bug, 🫴🏼 utils

#940 Fix obsolete noqa ruff
  dynamiqs/random/__init__.py
Labels: bug, 🪛 tooling

#939 Fix typo to emit warnings
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
Labels: bug, 🌀 solvers

#944 Update diffrax dependency to account for jax compatibility
  pyproject.toml
Labels: bug, 🪛 tooling

#938 Replace discontinuity times `None` default value by empty array
  dynamiqs/_utils.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/time_qarray.py
Labels: 🔧 technical, 🫴🏼 utils

#941 Replace warnings by errors for empty `jump_ops` in stochastic solvers
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/dssesolve.py
  dynamiqs/integrators/apis/jssesolve.py
Labels: bug, 🌀 solvers

#947 Restrict JAX version to <0.5.3
  pyproject.toml
Labels: bug, 🪛 tooling

#946 Update version v.0.3.1 -> v0.3.2
  dynamiqs/__init__.py
Labels: organisation, 🪛 tooling

#945 Adds forward mode support from diffrax
  docs/python_api/index.md
  dynamiqs/gradient.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/method.py
  mkdocs.yml
  tests/integrator_tester.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_rouchon.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
Labels: feature, 🌀 solvers

#948 Add check on initial state layout
  dynamiqs/_checks.py
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/mesolve.py
Labels: feature, 🌀 solvers
