Repository dynamiqs/dynamiqs, pull requests merged in 2025-01, with the labels that each got.

#890 Remove jaxlib dependency in toml
  pyproject.toml
Labels: bug, 🪛 tooling

#888 Rename dq.zero to dq.zeros
  docs/python_api/index.md
  dynamiqs/plot/wigner.py
  dynamiqs/utils/operators.py
  mkdocs.yml
  tests/utils/test_operators.py
Labels: feature, 🫴🏼 utils

#891 Change minimal Python version requirement from 3.9 to 3.10
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  README_PYPI.md
  docs/community/contributing.md
  dynamiqs/integrators/_utils.py
  dynamiqs/plot/hinton.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_primitives.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/utils/states.py
  pyproject.toml
  tests/mepropagator/mepropagator_utils.py
  tests/mesolve/test_batching.py
Labels: organisation, 🔧 technical

#889 Fix GPU support for eig following jax 0.4.36 release
  dynamiqs/_utils.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/utils/general.py
  pyproject.toml
Labels: feature, 🫴🏼 utils

#861 Add dq.hc
  .pre-commit-config.yaml
  docs/generate_python_api.py
  docs/python_api/index.md
  docs/templates/python/material/table.html.jinja
  dynamiqs/__init__.py
  dynamiqs/hermitian_conjugate.py
  mkdocs.yml
  tests/test_hermitian_conjugate.py
Labels: feature, 🫴🏼 utils

#887 Modify options to add support for local options
  docs/generate_python_api.py
  docs/python_api/options/Options.md
  docs/templates/python/material/class.html.jinja
  dynamiqs/conftest.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/floquet_integrator.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/options.py
  dynamiqs/result.py
  tests/mepropagator/test_expm.py
  tests/sepropagator/test_sepropagator.py
Labels: 📚 documentation, feature

#893 Fix Ruff A005 by making random a folder instead of a module
  docs/generate_python_api.py
  dynamiqs/plot/hinton.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/random/__init__.py
  dynamiqs/random/core.py
Labels: bug, 🪛 tooling

#895 Update version `v0.2.3` -> `v0.3.0`
  dynamiqs/__init__.py
Labels: organisation, 🪛 tooling

#892 Add runtime check for non-hermitian density matrix input
  dynamiqs/integrators/apis/mesolve.py
Labels: feature, 🌀 solvers

#897 Fix CI following Jax 0.5.0 release
  dynamiqs/random/core.py
Labels: bug, 🫴🏼 utils

#896 Improve spacing of Latex equations in docstrings
  docs/stylesheets/extra.css
Labels: 📚 documentation, feature

#881 Add indicative APIs for stochastic solvers
  docs/glossary.md
  docs/python_api/index.md
  docs/stylesheets/extra.css
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/dssesolve.py
  dynamiqs/integrators/apis/jsmesolve.py
  dynamiqs/integrators/apis/jssesolve.py
  dynamiqs/integrators/apis/smesolve.py
  dynamiqs/options.py
  dynamiqs/result.py
  dynamiqs/solver.py
  mkdocs.yml
Labels: 📚 documentation, feature

#877 Add a solver for the diffusive stochastic master equation (SME)
  README.md
  README_PYPI.md
  docs/documentation/advanced_examples/continuous-diffusive-measurement.md
  docs/documentation/getting_started/whatis.md
  docs/glossary.md
  dynamiqs/_checks.py
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/result.py
  mkdocs.yml
Labels: feature, 🌀 solvers

#900 Fix `y0` dims for `sepropagator` (and typo in timeqarray)
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/time_qarray.py
Labels: bug, 🌀 solvers

#899 Fix wrongly implemented __truediv__ in QArrays
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
Labels: bug, 🔧 technical
