Repository dynamiqs/dynamiqs, pull requests merged in 2025-02, with the labels that each got.

#898 Implement the operator sign utility
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/dark/__init__.py
  dynamiqs/dark/dark.py
  dynamiqs/qarrays/qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/utils/general.py
  mkdocs.yml
Labels: feature, 🫴🏼 utils

#902 Update version `v0.3.0` -> `v0.3.1`
  dynamiqs/__init__.py
Labels: organisation, 🪛 tooling

#903 Fix bug when summing qarrays with `sum()`
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
  dynamiqs/qarrays/dense_qarray.py
  dynamiqs/qarrays/sparsedia_qarray.py
  dynamiqs/qarrays/utils.py
  dynamiqs/utils/general.py
  dynamiqs/utils/vectorization.py
Labels: 🔧 technical, 🫴🏼 utils

#905 Use uv for the CI
  .github/workflows/ci.yml
  .github/workflows/publish-doc.yml
  .gitignore
Labels: organisation, 🪛 tooling

#906 Fix `signm` example to avoid the float precision 0 vs -0 sign doctest failure
  dynamiqs/utils/general.py
Labels: bug, 🎯 tests

#909 Add `dq.plot.xyz()` to plot Pauli operators expectation values for a qubit
  docs/python_api/index.md
  dynamiqs/plot/__init__.py
  dynamiqs/plot/qubit.py
  mkdocs.yml
Labels: feature, 🎨 plot

#907 Add `Rouchon1` solver for `dq.dsmesolve()`
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/rouchon_integrator.py
  dynamiqs/solver.py
Labels: feature, 🌀 solvers

#908 Add Euler-Maruyama solver to `dq.dssesolve()`
  docs/documentation/advanced_examples/continuous-diffusive-measurement.md
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/dssesolve.py
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/save_mixin.py
  dynamiqs/result.py
Labels: feature, 🌀 solvers

#913 Fix ruff error (module shadowing Python library)
  dynamiqs/random/__init__.py
Labels: bug, 🫴🏼 utils

#912 Update dates in licence and docs
  LICENSE
  mkdocs.yml
Labels: feature, organisation

#915 Revert "Rename "integrator" to "solver""
  docs/generate_python_api.py
  docs/python_api/index.md
  dynamiqs/__init__.py
  dynamiqs/integrators/__init__.py
  dynamiqs/integrators/_utils.py
  dynamiqs/integrators/apis/__init__.py
  dynamiqs/integrators/apis/dsmesolve.py
  dynamiqs/integrators/apis/dssesolve.py
  dynamiqs/integrators/apis/floquet.py
  dynamiqs/integrators/apis/jsmesolve.py
  dynamiqs/integrators/apis/jssesolve.py
  dynamiqs/integrators/apis/mepropagator.py
  dynamiqs/integrators/apis/mesolve.py
  dynamiqs/integrators/apis/sepropagator.py
  dynamiqs/integrators/apis/sesolve.py
  dynamiqs/integrators/core/__init__.py
  dynamiqs/integrators/core/abstract_integrator.py
  dynamiqs/integrators/core/diffrax_integrator.py
  dynamiqs/integrators/core/expm_integrator.py
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
  dynamiqs/integrators/core/floquet_integrator.py
  dynamiqs/integrators/core/interfaces.py
  dynamiqs/integrators/core/rouchon_integrator.py
  dynamiqs/integrators/core/save_mixin.py
  mkdocs.yml
  tests/floquet/floquet_qubit.py
  tests/integrator_tester.py
  tests/mepropagator/test_expm.py
  tests/mesolve/test_adaptive.py
  tests/mesolve/test_euler.py
  tests/mesolve/test_expm.py
  tests/mesolve/test_rouchon.py
  tests/sepropagator/test_sepropagator.py
  tests/sesolve/test_adaptive.py
  tests/sesolve/test_euler.py
  tests/sesolve/test_expm.py
Labels: organisation, 🌀 solvers

#917 Fix differentiability of `dq.wigner`
  dynamiqs/utils/wigner_utils.py
Labels: bug, 🫴🏼 utils

#911 Replace matrix-matrix mul with matrix-vector mul in `dssesolve`
  dynamiqs/integrators/core/fixed_step_stochastic_integrator.py
Labels: performance, 🌀 solvers

#918 Various minor fixes (typing, error message, documentation, argument renaming)
  docs/documentation/getting_started/sharp-bits.md
  dynamiqs/qarrays/qarray.py
  dynamiqs/time_qarray.py
  dynamiqs/utils/global_settings.py
Labels: bug, 🫴🏼 utils

#914 Add a warning in `dq.wigner()` when the state is not normalized
  dynamiqs/_checks.py
  dynamiqs/utils/wigner_utils.py
Labels: feature, 🫴🏼 utils

#920 Add temporary fix for latest JAX release
  pyproject.toml
Labels: bug, 🔧 technical

#921 Remove jax<0.5.1 requirement in dependencies
  pyproject.toml
Labels: bug, 🪛 tooling
